/**
 * seedCSSPart2.ts — Módulos 7 a 11 do Curso CSS (32 aulas)
 * NeuroCode · Metodologia ARPERC · lesson_rules.md
 */

import type { LessonInput, ModuleInput } from './seedCSSPart1';

// ─── helpers (re-exported helpers inline para evitar import circular) ──────────
const chk = (q: string, opts: string[], ci: number, exp: string) => ({
  question: q, options: opts, correctIndex: ci, explanation: exp
});

const blocks = (
  hookTxt: string,
  exATitle: string, exATxt: string, exACode: string,
  exBTitle: string, exBTxt: string, exBCode: string,
  pracTxt: string,
  checkpoint: ReturnType<typeof chk>,
  rewardTxt: string,
  prefix: string
) => ([
  { id: `hook-${prefix}`,   type: 'hook',       content: hookTxt },
  { id: `exp-${prefix}a`,   type: 'explain',    title: exATitle,  content: exATxt,  code: exACode },
  { id: `exp-${prefix}b`,   type: 'explain',    title: exBTitle,  content: exBTxt,  code: exBCode },
  { id: `prac-${prefix}`,   type: 'practice',   content: pracTxt },
  { id: `chk-${prefix}`,    type: 'checkpoint', content: 'Verificação rápida:', checkpoint },
  { id: `rew-${prefix}`,    type: 'reward',     content: rewardTxt },
]);

const mkLesson = (
  title: string, language: string, order: number,
  concept: string, template: string, validate: string,
  hookTxt: string,
  exATitle: string, exATxt: string, exACode: string,
  exBTitle: string, exBTxt: string, exBCode: string,
  pracTxt: string, checkpoint: ReturnType<typeof chk>, rewardTxt: string,
  prefix: string,
  chalInstr: string, h1: string, h2: string, h3: string
): LessonInput => ({
  title, language, order,
  codeTemplate: template,
  validationLogic: validate,
  content: JSON.stringify({
    title, concept,
    blocks: blocks(hookTxt, exATitle, exATxt, exACode, exBTitle, exBTxt, exBCode, pracTxt, checkpoint, rewardTxt, prefix),
    challenge: { instruction: chalInstr, hints: [h1, h2, h3] as [string,string,string] }
  })
});

// ─── MÓDULO 7 — Posicionamento ────────────────────────────────────────────────
const mod7: LessonInput[] = [

  mkLesson('A Propriedade Position','css',1,'Visão geral do position',
    `.elemento {\n  /* experimente position */\n  background-color: #7c3aed;\n  color: white;\n  padding: 16px;\n}`,
    `function v(o,c){return c.includes('position:');}v;`,
    'Elementos normais fluem no documento como palavras em um texto. Mas às vezes você precisa quebrar esse fluxo — colocar um elemento exatamente onde quiser na tela. Position faz isso.',
    'Os cinco valores de position',
    'static (padrão — no fluxo normal), relative (deslocado em relação à própria posição), absolute (posicionado em relação ao ancestral relativo), fixed (relativo à viewport), sticky (relativo até um ponto de rolagem).',
    `.elemento {\n  position: static;   /* padrão */\n  position: relative; /* deslocável */\n  position: absolute; /* fora do fluxo */\n  position: fixed;    /* fixo na tela */\n  position: sticky;   /* misto */\n}`,
    'Propriedades de deslocamento',
    'Junto com position, você usa top, right, bottom, left para mover o elemento. Eles só funcionam em elementos com position diferente de static.',
    `.box {\n  position: relative;\n  top: 20px;    /* desce 20px da posição original */\n  left: 30px;   /* avança 30px para a direita */\n}`,
    'Adicione position: relative ao .elemento do editor. Depois adicione top: 20px e left: 20px. Observe o deslocamento.',
    chk('Qual valor de position mantém o elemento no fluxo normal do documento?',['relative','absolute','fixed','static'],3,'static é o padrão. O elemento segue o fluxo normal do documento e ignora top/right/bottom/left. Todo elemento começa com position: static.'),
    'Você entende a base do posicionamento CSS! Nas próximas aulas, você vai dominar cada valor e criar layouts profissionais com sobreposição e elementos fixos.',
    'c37','Adicione position: relative ao .card com top: 10px e left: 10px. Observe que ele se desloca mas mantém o espaço original no fluxo.',
    'position: relative desloca o elemento da sua posição original mas mantém o espaço no fluxo.',
    'Combine com top, right, bottom ou left para definir o deslocamento.',
    'Código:\n.card { position: relative; top: 10px; left: 10px; }'
  ),

  mkLesson('Position Relative','css',2,'position: relative',
    `.container {\n  padding: 40px;\n  background-color: #f1f5f9;\n}\n.box {\n  background-color: #7c3aed;\n  color: white;\n  padding: 20px;\n  /* adicione position relative */\n}`,
    `function v(o,c){return c.includes('position:')&&c.includes('relative');}v;`,
    'relative é o mais "gentil" dos posicionamentos. O elemento se desloca da sua posição original, mas o espaço que ocupava é preservado — os outros elementos não se mexem.',
    'Como relative funciona',
    'position: relative usa top/right/bottom/left para deslocar o elemento RELATIVO à sua posição original no fluxo. Se você usar top: 20px, o elemento desce 20px de onde estaria normalmente.',
    `.box {\n  position: relative;\n  top: 20px;   /* 20px abaixo da posição original */\n  left: 40px;  /* 40px à direita da posição original */\n  /* O espaço original ainda é reservado no fluxo */\n}`,
    'Uso principal: âncora para absolute',
    'O uso mais importante de position: relative não é mover elementos — é criar um contexto de posicionamento para filhos com position: absolute. Na próxima aula, você verá por que isso é crucial.',
    `.card {\n  position: relative; /* âncora para o badge filho */\n}\n.badge {\n  position: absolute; /* se posiciona em relação ao .card */\n  top: 8px;\n  right: 8px;\n}`,
    'Adicione position: relative ao .box e experimente top: -20px (sobe) e left: 20px (move para direita). Depois remova e veja que o espaço volta.',
    chk('O que acontece com o espaço no fluxo de um elemento com position: relative deslocado?',['O espaço desaparece','Outros elementos ocupam o espaço','O espaço é preservado — outros elementos não se movem','O elemento volta para o início'],2,'position: relative preserva o espaço original do elemento no fluxo. Mesmo deslocado, o "buraco" onde ele estava continua existindo. Por isso outros elementos não se movem.'),
    'Você domina position: relative! Seu papel duplo — deslocar suavemente E criar contexto para absolute — é essencial em todo layout com sobreposição.',
    'c38','Crie .card com position: relative. Adicione um .badge filho com position: absolute, top: -8px, right: -8px, border-radius: 50% e background-color vermelho.',
    'O pai precisa de position: relative para servir de âncora ao filho absolute.',
    'O .badge com position: absolute vai se posicionar relativo ao .card (seu ancestral relative mais próximo).',
    'Código:\n.card { position: relative; }\n.badge { position: absolute; top: -8px; right: -8px; }'
  ),

  mkLesson('Position Absolute','css',3,'position: absolute',
    `.card {\n  position: relative;\n  width: 200px;\n  height: 150px;\n  background-color: #f1f5f9;\n}\n.etiqueta {\n  background-color: #7c3aed;\n  color: white;\n  padding: 4px 8px;\n  /* adicione position absolute */\n}`,
    `function v(o,c){return c.includes('position:')&&c.includes('absolute');}v;`,
    'Badges no canto de um card, tooltips flutuantes, overlays — todos usam position: absolute. É o posicionamento que tira o elemento do fluxo e o posiciona com coordenadas exatas.',
    'Como absolute funciona',
    'position: absolute remove o elemento do fluxo (os outros preenchem o espaço) e o posiciona relativo ao ancestral mais próximo com position diferente de static. Se não houver, é relativo ao viewport.',
    `.card {\n  position: relative; /* âncora */\n}\n.badge {\n  position: absolute;\n  top: 8px;    /* 8px do topo do .card */\n  right: 8px;  /* 8px da direita do .card */\n}`,
    'O contexto de posicionamento',
    'O "ancestral de referência" é o primeiro pai com position: relative/absolute/fixed/sticky. Por isso, sempre que usar absolute num filho, verifique se o pai tem position: relative. É a combinação mais comum em CSS.',
    `.tooltip {\n  position: absolute;\n  bottom: 110%; /* acima do pai */\n  left: 50%;\n  transform: translateX(-50%); /* centraliza horizontalmente */\n}`,
    'Adicione position: absolute à .etiqueta do editor. Use top: 8px e right: 8px. Observe como ela se posiciona dentro do .card (que tem position: relative).',
    chk('Em relação a quê um elemento position: absolute se posiciona?',['Sempre relativo ao body','Relativo ao viewport','Relativo ao ancestral mais próximo com position != static','Relativo ao irmão anterior'],2,'absolute se posiciona relativo ao ancestral mais próximo que tenha position: relative, absolute, fixed ou sticky. Se não houver, usa o body. Por isso sempre adicionamos position: relative no pai.'),
    'Você domina position: absolute! Essa é a base de badges, tooltips, menus dropdown, overlays e modais. Sempre lembre: o pai precisa de position: relative.',
    'c39','Crie .card com position: relative. Dentro, crie .novo-badge com position: absolute, top: 12px, left: 12px, background-color: #22c55e (verde), color: white, padding: 4px 10px.',
    'O pai PRECISA de position: relative para o filho absolute funcionar corretamente.',
    'top/left/right/bottom definem a distância das bordas do ancestral de referência.',
    'Código:\n.card { position: relative; }\n.novo-badge { position: absolute; top: 12px; left: 12px; background-color: #22c55e; color: white; padding: 4px 10px; }'
  ),

  mkLesson('Position Fixed','css',4,'position: fixed',
    `.navbar {\n  background-color: #0f172a;\n  color: white;\n  padding: 16px 24px;\n  /* torne a navbar fixa */\n}`,
    `function v(o,c){return c.includes('position:')&&c.includes('fixed');}v;`,
    'Você já viu barras de navegação que ficam no topo da tela enquanto você rola a página? Isso é position: fixed — o elemento fica preso na tela, ignorando a rolagem.',
    'Como fixed funciona',
    'position: fixed remove o elemento do fluxo e o posiciona em relação ao viewport (a janela do navegador). Mesmo ao rolar a página, o elemento permanece no mesmo lugar na tela.',
    `.navbar {\n  position: fixed;\n  top: 0;       /* fixo no topo */\n  left: 0;\n  right: 0;     /* largura total */\n  z-index: 100; /* acima de outros elementos */\n}`,
    'O problema do fixed e a solução',
    'fixed remove o elemento do fluxo — o conteúdo abaixo pode ficar escondido embaixo da navbar. A solução é adicionar padding-top (ou margin-top) no corpo da página igual à altura da navbar.',
    `body {\n  padding-top: 60px; /* compensa a navbar de 60px */\n}\n.navbar {\n  position: fixed;\n  top: 0;\n  height: 60px;\n}`,
    'Adicione position: fixed, top: 0, left: 0, right: 0 e z-index: 100 na .navbar. Observe como ela fica fixa mesmo na simulação.',
    chk('O que torna position: fixed diferente de absolute?',['fixed é mais rápido','fixed se posiciona relativo ao viewport e não muda ao rolar a página','fixed não precisa de elemento pai','Não há diferença prática'],1,'fixed é relativo ao viewport (janela do navegador) e não se move com a rolagem. absolute é relativo ao ancestral posicionado e rola junto com a página. A diferença é comportamento ao rolar.'),
    'Você cria navbars fixas com CSS! position: fixed é a escolha para headers, botões flutuantes, chats de suporte e qualquer elemento que precisa ficar sempre visível.',
    'c40','Crie .navbar com position: fixed, top: 0, left: 0, right: 0, height: 60px, background-color: #0f172a, z-index: 100. Adicione body { padding-top: 60px; }.',
    'position: fixed + top: 0 + left/right: 0 = navbar que fica no topo independente da rolagem.',
    'Sempre adicione padding-top no body igual à altura da navbar fixa, para o conteúdo não ficar escondido.',
    'Código:\n.navbar { position: fixed; top: 0; left: 0; right: 0; height: 60px; z-index: 100; background-color: #0f172a; }\nbody { padding-top: 60px; }'
  ),

  mkLesson('Position Sticky','css',5,'position: sticky',
    `.header-tabela {\n  background-color: #7c3aed;\n  color: white;\n  padding: 12px;\n  /* torne sticky */\n}`,
    `function v(o,c){return c.includes('position:')&&c.includes('sticky');}v;`,
    'sticky é o mais inteligente dos posicionamentos: o elemento se comporta como relative até atingir um ponto de rolagem — então "gruda" como fixed. Perfeito para cabeçalhos de tabela e subtítulos.',
    'Como sticky funciona',
    'position: sticky + top: 0 faz o elemento ficar no fluxo normal até o usuário rolar a ponto de ele sair da tela — aí ele "gruda" no topo. Quando a seção pai termina, ele sai junto.',
    `.secao-titulo {\n  position: sticky;\n  top: 60px; /* gruda a 60px do topo (abaixo da navbar) */\n  background-color: white;\n  padding: 12px 0;\n  z-index: 10;\n}`,
    'Diferença entre sticky e fixed',
    'fixed fica sempre visível independente do contexto. sticky fica visível SOMENTE dentro do pai — quando o pai sai da viewport, o sticky vai junto. Isso torna sticky ideal para cabeçalhos de seção.',
    `.modulo {\n  /* quando o módulo sai da tela, o título sticky vai junto */\n}\n.modulo .titulo {\n  position: sticky;\n  top: 0;\n  /* só gruda enquanto o .modulo estiver visível */\n}`,
    'Adicione position: sticky e top: 0 ao .header-tabela. Para testá-lo, você precisaria de conteúdo com rolagem — mas a regra está correta!',
    chk('Quando um elemento sticky "gruda" na tela?',['Sempre, como position: fixed','Somente quando o usuário passa o mouse sobre ele','Quando o usuário rola e o elemento está prestes a sair da viewport','Nunca — sticky é igual a relative'],2,'sticky combina relative e fixed: fica no fluxo normal até que a rolagem o leve ao threshold definido (ex: top: 0), então gruda. Só funciona dentro do contexto do elemento pai.'),
    'Você entende position: sticky! É a solução elegante para cabeçalhos que ficam visíveis durante a rolagem de uma seção específica — sem JavaScript!',
    'c41','Crie .section-header com position: sticky, top: 64px (abaixo de uma navbar de 64px), background-color: #0f172a, color: white, padding: 8px 24px, z-index: 10.',
    'sticky precisa de top (ou bottom/left/right) definido para saber quando "grudar".',
    'top: 64px significa que o elemento gruda quando está a 64px do topo da viewport — útil para ficar logo abaixo de uma navbar fixa de 64px.',
    'Código:\n.section-header { position: sticky; top: 64px; background-color: #0f172a; color: white; padding: 8px 24px; z-index: 10; }'
  ),

  mkLesson('Z-Index','css',6,'Propriedade z-index',
    `.caixa-a {\n  position: relative;\n  background-color: #7c3aed;\n  padding: 20px;\n  color: white;\n}\n.caixa-b {\n  position: relative;\n  background-color: #f97316;\n  padding: 20px;\n  color: white;\n  margin-top: -10px;\n  /* controle o z-index */\n}`,
    `function v(o,c){return c.includes('z-index:');}v;`,
    'Quando elementos se sobrepõem, qual fica na frente? Por padrão, o último no HTML fica acima. z-index é o controle manual dessa "pilha" de camadas.',
    'Como z-index funciona',
    'z-index aceita números inteiros (positivos, negativos ou zero). Maior número = mais à frente. Elementos com position: static ignoram z-index. O elemento deve ter position diferente de static.',
    `.modal {\n  position: fixed;\n  z-index: 1000; /* muito à frente */\n}\n.overlay {\n  position: fixed;\n  z-index: 999;  /* atrás do modal, mas na frente do resto */\n}\n.navbar {\n  position: sticky;\n  z-index: 100;\n}`,
    'Contexto de empilhamento',
    'z-index só funciona dentro do mesmo "contexto de empilhamento". Criar um novo contexto (com opacity < 1, transform, ou position com z-index) pode afetar como filhos se comportam. Na prática, use valores claros e consistentes.',
    `/* Escala de z-index recomendada: */\n--z-base:    0;\n--z-dropdown: 100;\n--z-sticky:   200;\n--z-fixed:    300;\n--z-overlay:  400;\n--z-modal:    500;\n--z-toast:    600;`,
    'Adicione z-index: 2 ao .caixa-a. Observe que ela fica na frente do .caixa-b (que aparece depois no HTML mas com z-index menor).',
    chk('O que é necessário para z-index funcionar?',['O elemento precisa ter display: block','O elemento precisa de position diferente de static','z-index sempre funciona em qualquer elemento','O elemento precisa estar dentro de um flex container'],1,'z-index só tem efeito em elementos posicionados — aqueles com position: relative, absolute, fixed ou sticky. Em elementos com position: static (padrão), z-index é ignorado.'),
    'Você controla a pilha de camadas com z-index! Navbars acima de tudo, modais acima de overlays, tooltips acima de cards — z-index define quem fica na frente de quem.',
    'c42','Crie uma escala: .navbar com z-index: 100, .modal com z-index: 500, .overlay com z-index: 499. Todos devem ter position definida.',
    'z-index só funciona em elementos com position: relative, absolute, fixed ou sticky.',
    'Use uma escala consistente: 100 para navegação, 200+ para sticky, 400+ para overlays, 500+ para modais.',
    'Código:\n.navbar { position: sticky; z-index: 100; }\n.overlay { position: fixed; z-index: 499; }\n.modal { position: fixed; z-index: 500; }'
  ),
];

// ─── MÓDULO 8 — Grid ──────────────────────────────────────────────────────────
const mod8: LessonInput[] = [

  mkLesson('Introdução ao CSS Grid','css',1,'display: grid',
    `.galeria {\n  /* ative o Grid */\n  background-color: #f1f5f9;\n  padding: 16px;\n}`,
    `function v(o,c){return c.includes('display:')&&c.includes('grid')&&!c.includes('inline-grid');}v;`,
    'Flexbox é excelente para uma dimensão (linha OU coluna). CSS Grid é para duas dimensões simultaneamente — linhas E colunas. É o sistema de layout mais poderoso do CSS.',
    'display: grid — ativando o Grid',
    'Assim como Flexbox, Grid funciona num contêiner. display: grid transforma os filhos em "grid items" que se organizam em células de uma grade. Você define quantas colunas e linhas existem.',
    `.galeria {\n  display: grid;\n  /* os filhos virão grid items */\n  /* defina colunas e linhas com grid-template */\n}`,
    'Grid vs Flexbox',
    'Use Flexbox para layouts lineares (navbar, row de botões, cards em linha). Use Grid para layouts bidimensionais (galeria, página completa, dashboard). As duas ferramentas se complementam.',
    `/* Flexbox = uma dimensão: */\n.navbar { display: flex; }\n\n/* Grid = duas dimensões: */\n.dashboard { display: grid; }`,
    'Ative display: grid no .galeria. Adicione grid-template-columns: 1fr 1fr 1fr para criar 3 colunas iguais e observe os filhos se organizando.',
    chk('Qual é a principal vantagem do CSS Grid sobre o Flexbox?',['Grid é mais rápido','Grid controla linhas e colunas simultaneamente (2D)','Grid funciona em mais navegadores','Grid não precisa de contêiner'],1,'Grid é bidimensional: controla linhas E colunas ao mesmo tempo. Flexbox é unidimensional (uma direção por vez). Para layouts complexos como páginas inteiras, Grid é muito mais poderoso.'),
    'Você ativou o CSS Grid! Essa é a ferramenta de layout mais avançada do CSS — com ela, você vai criar galerias, dashboards e layouts de página inteira com precisão.',
    'c43','Ative display: grid em .galeria. Adicione grid-template-columns: repeat(3, 1fr) para 3 colunas e gap: 16px.',
    'display: grid vai no CONTÊINER. Os filhos viram grid items automaticamente.',
    'grid-template-columns define quantas colunas e seus tamanhos. repeat(3, 1fr) = 3 colunas iguais.',
    'Código:\n.galeria { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }'
  ),

  mkLesson('Grid Template Columns','css',2,'Propriedade grid-template-columns',
    `.grid {\n  display: grid;\n  padding: 16px;\n  gap: 16px;\n  /* defina as colunas */\n}`,
    `function v(o,c){return c.includes('grid-template-columns:');}v;`,
    'grid-template-columns é onde você define o layout de colunas do Grid. Com ela, você especifica quantas colunas existem e qual é o tamanho de cada uma.',
    'Valores e a unidade fr',
    'fr (fraction) é a unidade exclusiva do Grid. 1fr representa "uma fração do espaço disponível". grid-template-columns: 1fr 2fr cria duas colunas onde a segunda tem o dobro da largura da primeira.',
    `.grid {\n  display: grid;\n  grid-template-columns: 200px 1fr;      /* fixo + flexível */\n  grid-template-columns: 1fr 1fr 1fr;    /* 3 iguais */\n  grid-template-columns: repeat(4, 1fr); /* 4 iguais */\n  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); /* responsivo */\n}`,
    'repeat() e minmax()',
    'repeat(3, 1fr) = 1fr 1fr 1fr (mais compacto). minmax(200px, 1fr) define tamanho mínimo e máximo. auto-fill preenche a linha com quantas colunas couberem. Essa combinação cria layouts responsivos sem media queries.',
    `.galeria {\n  display: grid;\n  /* Responsivo automático: colunas de no mínimo 200px */\n  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));\n  gap: 16px;\n}`,
    'Defina grid-template-columns: 1fr 2fr 1fr no .grid. Observe as três colunas com a do meio duas vezes maior. Depois tente repeat(3, 1fr).',
    chk('O que 1fr significa em CSS Grid?',['1 pixel de largura','1% do contêiner','Uma fração proporcional do espaço disponível','Um frame de animação'],2,'fr = fraction (fração). 1fr é uma parte do espaço livre. Em 1fr 2fr, a primeira coluna tem 1/3 e a segunda 2/3 do espaço total. O espaço é calculado após subtrair gaps e colunas fixas.'),
    'Você controla colunas do Grid com grid-template-columns! A unidade fr e a função repeat() são as ferramentas mais poderosas para criar layouts limpos e responsivos.',
    'c44','Crie .dashboard com display: grid, grid-template-columns: 240px 1fr, gap: 24px, min-height: 100vh. A primeira coluna será a sidebar fixa e a segunda o conteúdo.',
    'fr distribui o espaço restante proporcionalmente. 240px é fixo, 1fr pega tudo que sobra.',
    'repeat(auto-fill, minmax(min, max)) é o truque para grids responsivos automáticos.',
    'Código:\n.dashboard { display: grid; grid-template-columns: 240px 1fr; gap: 24px; min-height: 100vh; }'
  ),

  mkLesson('Grid Template Rows','css',3,'Propriedade grid-template-rows',
    `.layout {\n  display: grid;\n  grid-template-columns: 1fr;\n  min-height: 100vh;\n  /* defina as linhas */\n}`,
    `function v(o,c){return c.includes('grid-template-rows:');}v;`,
    'Enquanto grid-template-columns define a "largura" do grid, grid-template-rows define a "altura". Juntos, criam a grade completa de células.',
    'grid-template-rows',
    'Funciona igual ao columns: você define o tamanho de cada linha. auto ajusta a linha ao conteúdo. fr distribui o espaço disponível. Fixar a altura em px pode ser útil para layouts de página completa.',
    `.pagina {\n  display: grid;\n  grid-template-rows: 60px 1fr 80px;\n  /* header: 60px | main: cresce | footer: 80px */\n  min-height: 100vh;\n}`,
    'Layout de página clássico com Grid',
    'O layout header/main/footer em altura total é o caso de uso mais claro de grid-template-rows: 60px 1fr 80px + min-height: 100vh cria o layout de página completo de forma elegante.',
    `.app {\n  display: grid;\n  grid-template-columns: 240px 1fr;\n  grid-template-rows: 60px 1fr;\n  min-height: 100vh;\n  /* 4 células: navbar, topo-direito, sidebar, conteúdo */\n}`,
    'Defina grid-template-rows: 60px 1fr 80px no .layout. Isso cria header (60px), conteúdo flexível e footer (80px) numa página de altura total.',
    chk('O que o valor "auto" faz em grid-template-rows?',['Cria linhas automáticas','A linha se ajusta ao tamanho do conteúdo','Remove a linha','Define a linha como 1fr'],1,'auto em grid-template-rows ou columns faz a célula se ajustar ao tamanho do seu conteúdo — nem maior nem menor que o necessário.'),
    'Você controla linhas do Grid! Com grid-template-rows e grid-template-columns combinados, você cria layouts de página completa com precisão absoluta.',
    'c45','Crie .app com display: grid, grid-template-columns: 240px 1fr, grid-template-rows: 60px 1fr, min-height: 100vh — um layout de app clássico com sidebar e header.',
    'grid-template-rows define alturas das linhas. auto ajusta ao conteúdo, fr distribui o espaço.',
    '60px 1fr 80px = linha fixa + conteúdo flexível + linha fixa. Perfeito para header/main/footer.',
    'Código:\n.app { display: grid; grid-template-columns: 240px 1fr; grid-template-rows: 60px 1fr; min-height: 100vh; }'
  ),

  mkLesson('Gap no Grid','css',4,'Propriedade gap no Grid',
    `.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  /* adicione gap */\n}`,
    `function v(o,c){return (c.includes('gap:'))||c.includes('row-gap:')||c.includes('column-gap:');}v;`,
    'Assim como no Flexbox, gap no Grid cria espaçamento entre as células — mas agora em duas dimensões: entre linhas e entre colunas.',
    'gap no Grid: dois valores',
    'gap: 24px 16px define row-gap (entre linhas) e column-gap (entre colunas) separadamente. Um valor único aplica igual para ambos. É o mesmo gap do Flexbox, mas agora com controle bidirecional.',
    `.galeria {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 24px;        /* igual em todos os lados */\n  gap: 32px 16px;   /* 32px entre linhas, 16px entre colunas */\n  row-gap: 24px;    /* só entre linhas */\n  column-gap: 16px; /* só entre colunas */\n}`,
    'Gap na prática: galeria de imagens',
    'A combinação display: grid + grid-template-columns + gap é a forma mais elegante de criar galerias responsivas. Com repeat(auto-fill, minmax(200px, 1fr)) + gap: 16px, a galeria se adapta automaticamente.',
    `.galeria {\n  display: grid;\n  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));\n  gap: 16px;\n  padding: 16px;\n}`,
    'Adicione gap: 24px 16px ao .grid (3 colunas). Observe o espaçamento diferente entre linhas e colunas.',
    chk('Qual a diferença entre gap: 16px e gap: 16px 8px?',['Não há diferença','gap: 16px aplica 16px em todos os lados; gap: 16px 8px = 16px entre linhas e 8px entre colunas','gap: 16px 8px gera um erro','gap: 16px 8px aplica só em Grid, não em Flexbox'],1,'Com um valor: aplica o mesmo espaço em todas as direções. Com dois valores: o primeiro é row-gap (entre linhas) e o segundo é column-gap (entre colunas). A mesma lógica de shorthand do margin e padding.'),
    'Você controla espaçamento bidimensional com gap no Grid! Agora você tem controle total tanto do espaço entre linhas quanto entre colunas.',
    'c46','Crie .galeria com display: grid, grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)), gap: 24px e padding: 24px.',
    'gap com um valor aplica igual em linhas e colunas. Com dois valores: row-gap column-gap.',
    'auto-fill + minmax() é o truque do Grid responsivo: cria quantas colunas couberem de no mínimo 240px.',
    'Código:\n.galeria { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 24px; padding: 24px; }'
  ),

  mkLesson('Áreas de Grid','css',5,'grid-template-areas',
    `.layout {\n  display: grid;\n  grid-template-columns: 240px 1fr;\n  grid-template-rows: 60px 1fr 60px;\n  min-height: 100vh;\n  /* defina as áreas */\n}`,
    `function v(o,c){return c.includes('grid-template-areas:')&&c.includes('grid-area:');}v;`,
    'E se você pudesse "desenhar" o layout em texto? grid-template-areas faz exatamente isso — você nomeia as regiões e os elementos se posicionam nelas como peças de um quebra-cabeça.',
    'grid-template-areas: desenhando o layout',
    'No contêiner, você define as áreas com nomes entre aspas — como um mapa. Cada linha de texto é uma linha do grid. O ponto (.) representa uma célula vazia. Nos filhos, use grid-area: nome.',
    `.layout {\n  display: grid;\n  grid-template-columns: 240px 1fr;\n  grid-template-rows: 60px 1fr 60px;\n  grid-template-areas:\n    "navbar  navbar"\n    "sidebar main"\n    "footer  footer";\n}`,
    'Atribuindo elementos às áreas',
    'Cada filho do grid recebe grid-area: nome — o mesmo nome definido no template. Isso desacopla completamente o CSS do HTML: você pode reposicionar toda a página mudando só o template.',
    `/* Filhos do .layout: */\n.navbar  { grid-area: navbar; }\n.sidebar { grid-area: sidebar; }\n.main    { grid-area: main; }\n.footer  { grid-area: footer; }`,
    'Complete o .layout com grid-template-areas definindo "navbar navbar" / "sidebar main" / "footer footer". Atribua grid-area aos filhos.',
    chk('Como um elemento filho sabe qual área do Grid ocupar?',['Pela ordem que aparece no HTML','Pela propriedade grid-area com o nome da área','Automaticamente pela posição','Pelo atributo data-area=""'],1,'Você define a área no contêiner com grid-template-areas e nomeia cada elemento filho com grid-area: nomeDefinido. Isso é completamente declarativo — você lê o CSS e "vê" o layout.'),
    'Você criou layouts com áreas nomeadas! grid-template-areas é a propriedade mais legível e elegante do CSS Grid — você literalmente desenha o layout em texto.',
    'c47','Complete o layout com grid-template-areas: "navbar navbar" / "sidebar main" / "footer footer". Atribua .navbar { grid-area: navbar; }, .sidebar { grid-area: sidebar; }, .main { grid-area: main; }, .footer { grid-area: footer; }.',
    'grid-template-areas fica no CONTÊINER. grid-area fica nos FILHOS.',
    'Cada string entre aspas é uma linha do grid. O nome nas aspas corresponde ao grid-area do filho.',
    'Código:\n.layout { grid-template-areas: "navbar navbar" "sidebar main" "footer footer"; }\n.navbar { grid-area: navbar; }\n.sidebar { grid-area: sidebar; }\n.main { grid-area: main; }\n.footer { grid-area: footer; }'
  ),
];

// ─── MÓDULO 9 — Responsividade ────────────────────────────────────────────────
const mod9: LessonInput[] = [

  mkLesson('Unidades Relativas: visão geral','css',1,'Unidades relativas vs absolutas',
    `/* Experimente diferentes unidades */\nh1 {\n  /* font-size em px, rem e % */\n}`,
    `function v(o,c){return c.includes('rem')||c.includes('em')||c.includes('vw')||c.includes('vh')||c.includes('%');}v;`,
    'Telas de diferentes tamanhos existem — celular, tablet, desktop, TV. Unidades relativas são a chave para que o design funcione em todos sem regras específicas para cada.',
    'Absolutas vs relativas',
    'Unidades absolutas (px, cm, pt) têm tamanho fixo. Unidades relativas (%, rem, em, vw, vh) se adaptam ao contexto. Em CSS responsivo, unidades relativas são sempre preferidas.',
    `/* Absolutas (fixas): */\nh1 { font-size: 32px; } /* sempre 32px */\n\n/* Relativas (adaptáveis): */\nh1 { font-size: 2rem; }  /* 2x o tamanho base */\n.box { width: 50%; }     /* metade do pai */\n.hero { height: 100vh; } /* altura da tela */`,
    'Quando usar px',
    'px ainda tem seu lugar: bordas (1px solid), sombras (box-shadow), e dimensões de elementos que NUNCA devem mudar independente da tela (como um ícone de 24px). Para todo o resto, prefira unidades relativas.',
    `/* px para detalhes fixos: */\nborder: 1px solid #e2e8f0;\nborder-radius: 8px;\nbox-shadow: 0 2px 4px rgba(0,0,0,0.1);\n\n/* Relativas para dimensões: */\nfont-size: 1rem;\npadding: 1.5rem;\nmax-width: 65ch;`,
    'Escreva font-size em rem para h1, h2 e p. Use % para width de .container e vh para height de .hero.',
    chk('Qual unidade se adapta ao tamanho da janela do navegador?',['px','cm','rem','vw'],3,'vw (viewport width) é proporcional à largura da janela. 100vw = largura total. vh (viewport height) é proporcional à altura. Essas unidades mudam automaticamente quando a janela é redimensionada.'),
    'Você entende a diferença entre unidades! Agora você sabe quando usar cada uma. Nas próximas aulas, vamos detalhar cada unidade relativa.',
    'c48','Defina: h1 com font-size: 2.5rem, .container com max-width: 80% e margin: 0 auto, .hero com height: 100vh.',
    'rem é relativo à fonte raiz (geralmente 16px). % é relativo ao pai. vh é relativo à altura da tela.',
    'Misture: px para detalhes fixos, rem para tipografia, % para larguras, vh/vw para dimensões de tela.',
    'Código:\nh1 { font-size: 2.5rem; }\n.container { max-width: 80%; margin: 0 auto; }\n.hero { height: 100vh; }'
  ),

  mkLesson('Porcentagem','css',2,'Unidade %',
    `.container {\n  /* use porcentagem */\n  background-color: #f1f5f9;\n  padding: 20px;\n}`,
    `function v(o,c){return c.includes('%')&&c.includes(':');}v;`,
    'Porcentagem é a unidade relativa mais intuitiva: 50% é sempre metade do elemento pai. É a base de layouts fluidos — elementos que crescem e encolhem com o contêiner.',
    'Como % funciona',
    '% é sempre relativo ao elemento pai. width: 50% = metade da largura do pai. font-size: 150% = 1.5x a fonte do pai. Isso cria dependência hierárquica — mudar o pai muda todos os filhos.',
    `.container {\n  width: 90%;         /* 90% do pai (ex: body) */\n  max-width: 1200px;  /* mas nunca mais que 1200px */\n  margin: 0 auto;     /* centralizado */\n}\n.coluna {\n  width: 50%;         /* metade do .container */\n}`,
    'max-width: o melhor amigo de %',
    'width: 90% pode ser enorme em telas grandes. Combine sempre com max-width: para definir um limite máximo. width: 90%; max-width: 1200px é o padrão para contêineres principais.',
    `.wrapper {\n  width: 90%;\n  max-width: 1200px;\n  margin: 0 auto;\n  /* Funciona em celular (90% de 390px = 351px) */\n  /* E em desktop (max 1200px de 1920px) */\n}`,
    'Defina .container com width: 90%, max-width: 1200px e margin: 0 auto. Veja como o contêiner se adapta ao pai.',
    chk('A que é relativo width: 50% num elemento filho?',['50% da tela','50% do browser','50% do elemento pai direto','50% do body sempre'],2,'width em % é relativo ao width do elemento pai. Se o pai tem 800px, width: 50% = 400px. Se o pai tem 400px, width: 50% = 200px. É sempre proporcional ao pai imediato.'),
    'Você usa porcentagem em CSS! width: 90%; max-width: 1200px; margin: 0 auto é o padrão de container responsivo mais usado na web.',
    'c49','Crie .wrapper com width: 90%, max-width: 1280px, margin: 0 auto e padding: 0 24px.',
    '% é relativo ao pai. Combine width: 90% com max-width para limitar em telas grandes.',
    'margin: 0 auto centraliza o elemento quando ele tem width menor que o pai.',
    'Código:\n.wrapper { width: 90%; max-width: 1280px; margin: 0 auto; padding: 0 24px; }'
  ),

  mkLesson('Unidade vw','css',3,'Unidade vw (viewport width)',
    `.hero {\n  /* use vw para dimensões relativas à tela */\n  background-color: #0f172a;\n  color: white;\n}`,
    `function v(o,c){return c.includes('vw')&&c.includes(':');}v;`,
    'vw (viewport width) é proporcional à largura da janela. 100vw = largura total da tela. É a unidade certa para elementos que precisam ocupar a tela inteira independente do tamanho.',
    'vw na prática',
    '1vw = 1% da largura do viewport. 100vw = largura total. Útil para seções hero, banners fullscreen e tipografia fluida. Cuidado: 100vw inclui a largura da scrollbar (pode causar overflow).',
    `.hero {\n  width: 100vw;          /* largura total da tela */\n  /* Ou prefira: */\n  width: 100%;           /* sem risco de overflow */\n}\n.titulo-fluido {\n  font-size: clamp(2rem, 5vw, 4rem); /* cresce com a tela */\n}`,
    'vw para tipografia fluida',
    'font-size: 5vw cria tipografia que cresce com a tela. Combine com clamp(mínimo, preferido, máximo) para definir limites: clamp(1.5rem, 3vw, 3rem) = nunca menor que 1.5rem, nunca maior que 3rem.',
    `h1 {\n  /* Tipografia fluida com limites: */\n  font-size: clamp(2rem, 5vw, 4rem);\n  /* celular: 2rem | tablet: proporcional | desktop: 4rem */\n}`,
    'Adicione width: 100vw ao .hero. Observe como ocupa toda a largura da tela. Depois experimente font-size: clamp(2rem, 5vw, 4rem) em um h1.',
    chk('Qual problema pode ocorrer com width: 100vw?',['O elemento some','O elemento causa overflow horizontal por incluir a largura da scrollbar','A cor de fundo não aparece','O texto não aparece'],1,'100vw inclui a largura da scrollbar vertical. Isso pode causar uma barra de rolagem horizontal indesejada. A solução é usar width: 100% no lugar — que respeita o contexto do contêiner.'),
    'Você usa vw para dimensionar elementos relativo à tela! A função clamp() com vw é o segredo da tipografia fluida moderna.',
    'c50','Use font-size: clamp(2rem, 5vw, 4rem) no h1 principal. Use width: 100% (não vw) no .hero para evitar overflow.',
    'vw = viewport width. 5vw = 5% da largura da tela.',
    'clamp(min, preferido, max) garante que o valor fique sempre entre os limites — ótimo para tipografia fluida.',
    'Código:\nh1 { font-size: clamp(2rem, 5vw, 4rem); }\n.hero { width: 100%; min-height: 100vh; }'
  ),

  mkLesson('Unidade vh','css',4,'Unidade vh (viewport height)',
    `.hero {\n  /* use vh para altura relativa à tela */\n  background-color: #0f172a;\n  color: white;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}`,
    `function v(o,c){return c.includes('vh')&&c.includes(':');}v;`,
    '100vh é a altura da tela — e é a forma mais simples de criar seções "fullscreen" sem calcular nada. É o vh que torna possível os modernos "scroll stories" de sites criativos.',
    'vh na prática',
    '1vh = 1% da altura do viewport. 100vh = altura total da tela. min-height: 100vh (em vez de height: 100vh) é preferível — garante que a seção seja pelo menos 100% da tela, mas pode crescer com o conteúdo.',
    `.hero {\n  min-height: 100vh; /* prefira min-height */\n}\n.section {\n  min-height: 50vh; /* pelo menos metade da tela */\n}`,
    'O problema do vh em mobile',
    'Em mobile, a barra do navegador aparece e desaparece ao rolar, mudando o vh. O valor dvh (dynamic viewport height) resolve isso. Em CSS moderno: min-height: 100dvh; com fallback: min-height: 100vh.',
    `.hero {\n  min-height: 100vh;  /* fallback para navegadores antigos */\n  min-height: 100dvh; /* moderno: considera a barra do navegador */\n}`,
    'Adicione min-height: 100vh ao .hero. Com display: flex e align-items: center já presentes, o conteúdo ficará perfeitamente centralizado na tela.',
    chk('Por que preferir min-height: 100vh em vez de height: 100vh?',['min-height é mais rápido','min-height permite que o elemento cresça além de 100vh se o conteúdo precisar','height: 100vh não funciona','São equivalentes'],1,'height: 100vh trava a altura exatamente na tela — se o conteúdo for maior, haverá overflow. min-height: 100vh garante o mínimo de 100vh, mas permite crescer. Para seções hero com conteúdo variável, min-height é muito mais seguro.'),
    'Você usa vh para criar seções fullscreen! min-height: 100vh + display: flex + align-items: center é a tríade perfeita para seções hero impactantes.',
    'c51','Crie .hero com min-height: 100vh, display: flex, flex-direction: column, align-items: center, justify-content: center e background-color: #0f172a.',
    'vh é a altura da viewport. 100vh = altura total da tela.',
    'Prefira min-height: 100vh para que o conteúdo possa crescer se necessário.',
    'Código:\n.hero { min-height: 100vh; display: flex; flex-direction: column; align-items: center; justify-content: center; }'
  ),

  mkLesson('Unidade rem','css',5,'Unidade rem',
    `html {\n  font-size: 16px; /* base */\n}\nh1 {\n  /* use rem */\n}\np {\n  \n}`,
    `function v(o,c){return c.includes('rem')&&c.includes(':');}v;`,
    'rem (root em) é a unidade ideal para tipografia acessível. Ela é relativa ao tamanho de fonte do elemento html — e respeita quando o usuário aumenta o tamanho da fonte no navegador.',
    'Como rem funciona',
    'Se html { font-size: 16px }, então 1rem = 16px, 2rem = 32px, 0.875rem ≈ 14px. A vantagem: se o usuário mudar o tamanho de fonte padrão do navegador, TUDO que usa rem se ajusta automaticamente.',
    `html { font-size: 16px; }\n\nh1 { font-size: 3rem; }     /* 48px */\nh2 { font-size: 2rem; }     /* 32px */\np  { font-size: 1rem; }     /* 16px */\nsmall { font-size: 0.875rem; } /* 14px */`,
    'rem para espaçamento consistente',
    'Use rem também para padding, margin e gap — assim todo o espaçamento escala junto com a tipografia. Isso cria um sistema de design consistente onde aumentar o tamanho base aumenta tudo proporcionalmente.',
    `.card {\n  padding: 1.5rem;      /* 24px */\n  margin-bottom: 1rem;  /* 16px */\n  border-radius: 0.5rem; /* 8px */\n}`,
    'Defina h1 com 3rem, h2 com 2rem e p com 1rem. Observe a hierarquia tipográfica proporcional.',
    chk('Por que rem é preferível a px para tipografia?',['rem carrega mais rápido','rem respeita as preferências de tamanho de fonte do usuário no navegador','rem é mais fácil de calcular','Não há diferença prática'],1,'rem escala com a preferência de fonte do usuário. Se alguém configura fonte maior no navegador por dificuldade visual, sites com rem se adaptam. Sites com px ficam fixos — inacessíveis.'),
    'Você usa rem para tipografia acessível! Essa escolha beneficia usuários com baixa visão e torna o design mais inclusivo sem nenhum custo extra.',
    'c52','Crie um sistema tipográfico completo com rem: h1: 3rem, h2: 2.25rem, h3: 1.75rem, p: 1.125rem, small: 0.875rem.',
    'rem é relativo ao html. Se html { font-size: 16px }, 1rem = 16px.',
    'Use rem para tipografia e espaçamentos para criar um sistema que escala junto.',
    'Código:\nh1 { font-size: 3rem; }\nh2 { font-size: 2.25rem; }\nh3 { font-size: 1.75rem; }\np { font-size: 1.125rem; }\nsmall { font-size: 0.875rem; }'
  ),

  mkLesson('Unidade em','css',6,'Unidade em',
    `.card {\n  font-size: 16px;\n  /* experimente em nos filhos */\n}\n.card .titulo {\n  \n}`,
    `function v(o,c){var lines=c.split('\\n');return lines.some(l=>l.includes('em')&&l.includes(':')&&!l.includes('rem')&&!l.includes('html')&&!l.includes('font-family'));}v;`,
    'em é irmã do rem — mas com comportamento diferente. Enquanto rem é sempre relativo ao html, em é relativo ao elemento pai imediato. Isso cria uma cascata de escalas proporcional.',
    'Como em funciona',
    'Se o pai tem font-size: 20px, então 1em = 20px para os filhos. 1.5em = 30px. O problema: efeito cascata. Se você aninhar elementos com font-size: 1.5em, cada nível vai escalar — potencialmente causando efeitos inesperados.',
    `.pai {\n  font-size: 20px;\n}\n.filho {\n  font-size: 1.5em; /* 30px (1.5 × 20px) */\n}\n.neto {\n  font-size: 1.5em; /* 45px (1.5 × 30px) — cuidado! */\n}`,
    'Quando usar em vs rem',
    'Use rem para tamanhos de fonte no documento inteiro (consistência global). Use em para padding/margin RELATIVOS ao font-size do próprio elemento — assim botões e badges escalam com o texto internamente.',
    `.btn {\n  font-size: 1rem;       /* tamanho base com rem */\n  padding: 0.75em 1.5em; /* padding em em — escala com a fonte do botão */\n  /* Se mudar o font-size do botão, o padding se ajusta */\n}`,
    'No .card com font-size: 16px, use em nos filhos. Mude font-size do .card e veja como os filhos se ajustam.',
    chk('Qual a diferença principal entre rem e em?',['São idênticos','rem é relativo ao html; em é relativo ao elemento pai','rem é para fontes; em é para espaçamentos','em funciona só em flex containers'],1,'rem (root em) sempre é relativo ao html — fixo e previsível. em é relativo ao pai imediato — proporcional mas pode causar efeito cascata. Use rem para fontes globais e em para espaçamentos internos de componentes.'),
    'Você entende em! O uso inteligente de em para padding em botões e badges é um padrão profissional — permite escalar o componente apenas mudando o font-size.',
    'c53','Use em para padding em .btn: padding: 0.75em 1.5em. Agora mude font-size do .btn e observe que o padding se ajusta proporcionalmente.',
    'em é relativo ao elemento pai. Em padding do próprio elemento, em é relativo ao seu próprio font-size.',
    'Prefira rem para font-size global e em para padding/margin internos de componentes que precisam escalar.',
    'Código:\n.btn { font-size: 1rem; padding: 0.75em 1.5em; border-radius: 0.5em; }'
  ),

  mkLesson('Media Queries','css',7,'@media — Queries de responsividade',
    `/* Layout padrão (mobile first) */\n.container {\n  display: block;\n}\n\n/* Adicione @media abaixo */\n`,
    `function v(o,c){return c.includes('@media')&&c.includes('{');}v;`,
    'Media queries são os "detectores de tela" do CSS. Com elas, você muda estilos com base no tamanho da tela — a base da responsividade web.',
    'Sintaxe da @media',
    '@media (condição) { regras CSS }. A condição mais comum é max-width (aplica até aquele tamanho) ou min-width (aplica a partir daquele tamanho). Mobile-first usa min-width (estilos base para mobile, adições para desktop).',
    `/* Desktop-first (evite): */\n@media (max-width: 768px) {\n  .menu { display: none; } /* esconde em mobile */\n}\n\n/* Mobile-first (prefira): */\n.menu { display: none; } /* oculto no mobile */\n@media (min-width: 768px) {\n  .menu { display: flex; } /* visível no desktop */\n}`,
    'Breakpoints comuns',
    'Breakpoints são os pontos onde o layout muda. Os mais usados: 640px (sm — smartphone grande), 768px (md — tablet), 1024px (lg — desktop pequeno), 1280px (xl — desktop padrão), 1536px (2xl — desktop grande).',
    `/* Sistema de breakpoints: */\n@media (min-width: 640px)  { /* sm */ }\n@media (min-width: 768px)  { /* md */ }\n@media (min-width: 1024px) { /* lg */ }\n@media (min-width: 1280px) { /* xl */ }`,
    'Adicione @media (min-width: 768px) ao editor. Dentro, mude .container de display: block para display: flex. Isso simula mobile-first responsividade.',
    chk('O que significa "mobile-first" em CSS?',['O site funciona só em mobile','Você escreve estilos base para mobile e usa @media min-width para adicionar estilos em telas maiores','O CSS mobile é carregado antes do desktop','Você só usa % e vh/vw'],1,'Mobile-first: estilos base atendem mobile (sem @media). Media queries com min-width adicionam complexidade progressivamente para telas maiores. É o oposto de desktop-first (max-width). Mobile-first é o padrão moderno.'),
    'Você escreve media queries! Essa é a habilidade que transforma um site bonito no desktop em uma experiência perfeita em qualquer dispositivo.',
    'c54','Escreva base mobile: .grid { display: block; }. Em @media (min-width: 768px): .grid { display: grid; grid-template-columns: 1fr 1fr; }. Em @media (min-width: 1024px): .grid { grid-template-columns: repeat(3, 1fr); }.',
    '@media (min-width: Xpx) { } aplica estilos somente em telas com aquela largura mínima.',
    'Mobile-first: comece sem @media (mobile). Adicione @media min-width para tablet e desktop.',
    'Código:\n.grid { display: block; }\n@media (min-width: 768px) { .grid { display: grid; grid-template-columns: 1fr 1fr; } }\n@media (min-width: 1024px) { .grid { grid-template-columns: repeat(3, 1fr); } }'
  ),
];

// ─── MÓDULO 10 — Animações ────────────────────────────────────────────────────
const mod10: LessonInput[] = [

  mkLesson('Transition','css',1,'Propriedade transition',
    `.btn {\n  background-color: #7c3aed;\n  color: white;\n  padding: 12px 24px;\n  border-radius: 8px;\n  cursor: pointer;\n  /* adicione transition */\n}\n.btn:hover {\n  background-color: #5b21b6;\n  transform: translateY(-3px);\n}`,
    `function v(o,c){return c.includes('transition:');}v;`,
    'Sem transition, mudanças de hover são instantâneas e bruscas. Com transition, toda mudança visual se torna uma animação suave e profissional.',
    'Sintaxe de transition',
    'transition: propriedade duração função-de-timing delay. O shorthand "all 0.3s ease" é o mais usado: anima todas as propriedades por 0.3 segundos com aceleração suave.',
    `.btn {\n  transition: all 0.2s ease;\n  /* ou específico: */\n  transition: background-color 0.3s ease, transform 0.2s ease;\n}`,
    'Funções de timing',
    'ease (padrão — começa rápido, termina devagar), linear (velocidade constante), ease-in (começa devagar), ease-out (termina devagar), ease-in-out (começa e termina devagar). Para micro-interações, ease-out é o mais natural.',
    `.card {\n  transition: box-shadow 0.3s ease-out,\n              transform 0.2s ease-out;\n}\n.card:hover {\n  box-shadow: 0 8px 30px rgba(0,0,0,0.15);\n  transform: translateY(-4px);\n}`,
    'Adicione transition: all 0.2s ease no .btn. Depois passe o mouse e observe a mudança suave de cor e posição.',
    chk('Por que transition deve ficar na regra BASE e não no :hover?',['É mais performático','Garante que a animação aconteça tanto ao entrar quanto ao sair do hover','É obrigatório por especificação CSS','Não importa onde fica'],1,'Se transition estiver só no :hover, a animação acontece ao entrar mas não ao sair (volta instantânea). Na regra base, a animação funciona nas duas direções: entrada e saída do hover.'),
    'Você anima elementos com transition! Essa simples propriedade eleva qualquer interface de "funcional" para "polida". É o detalhe que faz usuários dizerem "que profissional!".',
    'c55','Adicione transition: all 0.25s ease no .btn e no .card. Defina .card:hover com transform: translateY(-8px) e box-shadow: 0 12px 30px rgba(0,0,0,0.15).',
    'transition fica na regra BASE (não no :hover) para animar nos dois sentidos.',
    'all 0.25s ease = anima TODAS as propriedades em 0.25 segundos com timing ease.',
    'Código:\n.card { transition: all 0.25s ease; }\n.card:hover { transform: translateY(-8px); box-shadow: 0 12px 30px rgba(0,0,0,0.15); }'
  ),

  mkLesson('Transform — Visão Geral','css',2,'Propriedade transform',
    `.caixa {\n  background-color: #7c3aed;\n  width: 100px;\n  height: 100px;\n  /* experimente transform */\n}`,
    `function v(o,c){return c.includes('transform:');}v;`,
    'transform é a propriedade que move, gira, escala e inclina elementos CSS — sem afetar o layout de outros elementos. É a base de animações modernas e efeitos visuais.',
    'Funções do transform',
    'transform aceita funções: translate(x,y) move, scale(n) redimensiona, rotate(ang) gira, skew(ang) inclina. Você pode combinar várias: transform: scale(1.1) rotate(5deg).',
    `.elemento {\n  transform: translate(20px, 10px); /* mover */\n  transform: scale(1.5);           /* escalar 150% */\n  transform: rotate(45deg);        /* girar */\n  transform: skew(10deg);          /* inclinar */\n  /* Combinados: */\n  transform: scale(1.05) translateY(-4px);\n}`,
    'Por que transform é performático',
    'transform (e opacity) são as únicas propriedades CSS que o navegador pode animar usando a GPU, sem recalcular o layout. Por isso, prefira transform: translateY() a position + top para animações suaves.',
    `/* Animação performática: */\n.btn:hover {\n  transform: translateY(-3px); /* GPU — suave */\n}\n/* Evite para animações: */\n.btn:hover {\n  position: relative; top: -3px; /* CPU — brusco */\n}`,
    'Experimente no editor: transform: scale(1.2) no .caixa. Depois tente rotate(15deg) e combine os dois.',
    chk('Por que transform é preferido para animações?',['É mais fácil de digitar','transform usa a GPU, não recalcula layout — animações mais suaves','transform funciona sem transition','Não há diferença de performance'],1,'transform e opacity são compostos pela GPU — o navegador não precisa recalcular o layout da página. Outras propriedades (width, top, left) causam recálculo de layout (reflow), que é muito mais custoso e causa travamentos.'),
    'Você entende transform! Nas próximas aulas, você vai dominar cada função separadamente. Transform + transition é a dupla das animações profissionais em CSS.',
    'c56','Combine scale e rotate: .caixa { transform: scale(1.1) rotate(10deg); }. Adicione transition: transform 0.3s ease e veja a animação no hover.',
    'transform aceita múltiplas funções separadas por espaço: scale(1.1) rotate(10deg).',
    'Sempre combine transform com transition para criar animações suaves.',
    'Código:\n.caixa { transition: transform 0.3s ease; }\n.caixa:hover { transform: scale(1.1) rotate(10deg); }'
  ),

  mkLesson('Transform Scale','css',3,'transform: scale()',
    `.card {\n  background-color: white;\n  padding: 20px;\n  border-radius: 12px;\n  transition: transform 0.2s ease;\n  /* adicione scale no hover abaixo */\n}\n.card:hover {\n  \n}`,
    `function v(o,c){return c.includes('scale(');}v;`,
    'scale() aumenta ou diminui um elemento visualmente sem mudar o layout. É o efeito de "zoom" que faz cards parecerem interativos.',
    'Valores de scale()',
    'scale(1) = tamanho original. scale(1.1) = 10% maior. scale(0.9) = 10% menor. scale(1.5) = 50% maior. Você pode escalar X e Y separadamente: scaleX(2) estica horizontalmente, scaleY(0.5) comprime verticalmente.',
    `.card:hover {\n  transform: scale(1.05); /* 5% maior no hover */\n}\n.botao:active {\n  transform: scale(0.96); /* leve "pressão" ao clicar */\n}`,
    'transform-origin',
    'Por padrão, scale() expande do centro. transform-origin muda o ponto de origem. transform-origin: top left expande do canto superior esquerdo. transform-origin: bottom center expande de baixo.',
    `.card {\n  transform-origin: center; /* padrão */\n}\n.tag:hover {\n  transform: scale(1.2);\n  transform-origin: left center; /* expande para a direita */\n}`,
    'Adicione transform: scale(1.05) no .card:hover do editor. Com a transition já presente, observe o efeito suave de "crescimento".',
    chk('O que transform: scale(0.5) faz?',['Remove o elemento','Reduz o elemento para 50% do tamanho visual sem mudar o layout','Move o elemento para baixo 50%','Reduz o elemento e o espaço que ocupa'],1,'scale() redimensiona visualmente sem mudar o layout. scale(0.5) mostra o elemento na metade do tamanho, mas o espaço original é preservado. Isso é diferente de mudar width/height.'),
    'Você usa scale() em animações! O efeito de leve crescimento no hover (1.03 a 1.07) é um dos padrões de UX mais eficazes para indicar interatividade.',
    'c57','Adicione scale(1.03) no .card:hover e scale(0.97) no .btn:active (simula pressão). Garanta transition: transform 0.2s ease na regra base.',
    'scale() aumenta ou diminui visualmente. 1 = 100%, 1.1 = 110%, 0.9 = 90%.',
    'O efeito :active com scale menor que 1 simula o botão sendo pressionado — ótima micro-interação.',
    'Código:\n.card { transition: transform 0.2s ease; }\n.card:hover { transform: scale(1.03); }\n.btn:active { transform: scale(0.97); }'
  ),

  mkLesson('Transform Rotate','css',4,'transform: rotate()',
    `.icone {\n  display: inline-block;\n  font-size: 2rem;\n  transition: transform 0.3s ease;\n}\n.icone:hover {\n  /* adicione rotate */\n}`,
    `function v(o,c){return c.includes('rotate(');}v;`,
    'Setas que giram para indicar menu aberto, ícones que rodam ao carregar, decorações dinâmicas — rotate() gira elementos com precisão angular.',
    'rotate() e os graus',
    'rotate(45deg) gira 45° no sentido horário. rotate(-45deg) gira no sentido anti-horário. rotate(360deg) gira completamente. Você também pode usar turn: rotate(0.5turn) = 180°.',
    `.seta:hover {\n  transform: rotate(180deg); /* gira 180° ao hover */\n}\n.spinner {\n  animation: girar 1s linear infinite;\n}\n@keyframes girar {\n  to { transform: rotate(360deg); }\n}`,
    'rotate + transition para efeitos de menu',
    'Um padrão muito usado em accordions e menus: uma seta (▾) gira 180° ao abrir. Isso é feito com rotate(180deg) no :hover ou ao adicionar uma classe via JavaScript.',
    `.accordion-seta {\n  transition: transform 0.3s ease;\n}\n.accordion-aberto .accordion-seta {\n  transform: rotate(180deg); /* seta apontando para cima */\n}`,
    'Adicione transform: rotate(180deg) no .icone:hover do editor. Com transition na regra base, observe a rotação suave.',
    chk('Qual valor gira um elemento no sentido anti-horário?',['rotate(+90deg)','rotate(-90deg)','rotate(270deg clockwise)','rotate(ccw 90deg)'],1,'Valores negativos giram no sentido anti-horário. rotate(-90deg) = 90° anti-horário. rotate(270deg) = mesmo efeito visual, mas no sentido horário (270° horário = 90° anti-horário).'),
    'Você gira elementos com rotate()! O efeito de seta que gira em accordions e menus dropdown é um dos padrões de UX mais reconhecíveis da web.',
    'c58','Crie .chevron com transition: transform 0.3s ease. No .aberto .chevron, adicione transform: rotate(180deg). Isso simula um accordeon com seta girando.',
    'rotate() aceita graus (deg) ou turns. 180deg = meia volta. 360deg = volta completa.',
    'Valores negativos giram no sentido anti-horário: rotate(-90deg).',
    'Código:\n.chevron { transition: transform 0.3s ease; }\n.aberto .chevron { transform: rotate(180deg); }'
  ),

  mkLesson('Transform Translate','css',5,'transform: translate()',
    `.notificacao {\n  background-color: #ef4444;\n  color: white;\n  padding: 16px 24px;\n  border-radius: 8px;\n  /* adicione translate */\n  transition: transform 0.3s ease-out;\n}`,
    `function v(o,c){return c.includes('translate')&&c.includes('(');}v;`,
    'translate() move um elemento sem afetar o layout — diferente de margin ou position. É a forma mais performática de mover elementos e a base de animações de "entrada" e "saída".',
    'translate: X e Y',
    'translateX() move horizontalmente, translateY() move verticalmente, translate(x,y) faz os dois. Valores positivos: direita/baixo. Valores negativos: esquerda/cima.',
    `.btn:hover {\n  transform: translateY(-4px); /* sobe 4px */\n}\n.menu {\n  transform: translateX(-100%); /* escondido à esquerda */\n}\n.menu.aberto {\n  transform: translateX(0); /* visível */\n}`,
    'translate para centralizar',
    'translate(-50%, -50%) combinado com position: absolute + top: 50% + left: 50% centraliza absolutamente um elemento independente do seu tamanho. É o truque mais clássico para centralização dinâmica.',
    `.modal {\n  position: absolute;\n  top: 50%;\n  left: 50%;\n  transform: translate(-50%, -50%);\n  /* perfeito no centro, independente do tamanho */\n}`,
    'Adicione transform: translateY(-100%) na .notificacao. Isso simula ela entrando de fora da tela. Depois mude para translateY(0) e veja o movimento.',
    chk('O que translateX(-100%) faz?',['Remove o elemento','Move o elemento 100% da própria largura para a esquerda','Move o elemento 100px para a esquerda','Deixa o elemento com 0% de opacidade'],1,'translateX(-100%) move o elemento pelo valor equivalente a 100% da sua PRÓPRIA largura para a esquerda. É muito usado para animar entradas/saídas de menus laterais.'),
    'Você usa translate() para mover elementos! Junto com transition, translate é a base de sidebars deslizantes, notificações que aparecem e modais que entram suavemente.',
    'c59','Crie .sidebar com transform: translateX(-100%) (oculta). Crie .sidebar.visivel com transform: translateX(0) e transition: transform 0.3s ease.',
    'translateX(-100%) move o elemento para fora da tela à esquerda (100% da sua largura).',
    'Para deslizar de volta: translateX(0). Com transition, vira uma animação suave de entrada.',
    'Código:\n.sidebar { transform: translateX(-100%); transition: transform 0.3s ease; }\n.sidebar.visivel { transform: translateX(0); }'
  ),

  mkLesson('Animações com @keyframes','css',6,'@keyframes e animation',
    `.spinner {\n  width: 40px;\n  height: 40px;\n  border: 4px solid #e2e8f0;\n  border-top-color: #7c3aed;\n  border-radius: 50%;\n  /* adicione animation */\n}`,
    `function v(o,c){return c.includes('@keyframes')&&c.includes('animation:');}v;`,
    'transition anima entre dois estados (normal e hover). @keyframes cria animações mais complexas com múltiplos passos — loops, sequências, entradas dramáticas. É o cinema do CSS.',
    '@keyframes: definindo a coreografia',
    '@keyframes define os "quadros" da animação. from/to definem início e fim. Você pode usar percentagens para pontos intermediários. A animação é então aplicada com a propriedade animation.',
    `@keyframes girar {\n  from { transform: rotate(0deg); }\n  to   { transform: rotate(360deg); }\n}\n\n@keyframes pulsar {\n  0%   { transform: scale(1); }\n  50%  { transform: scale(1.1); }\n  100% { transform: scale(1); }\n}`,
    'Propriedade animation',
    'animation: nome duração timing delay iterações direção. animation: girar 1s linear infinite cria rotação contínua. animation-fill-mode: forwards faz o elemento manter o estado final após a animação.',
    `.spinner {\n  animation: girar 0.8s linear infinite;\n}\n.entrada {\n  animation: fadeIn 0.5s ease-out forwards;\n}\n@keyframes fadeIn {\n  from { opacity: 0; transform: translateY(20px); }\n  to   { opacity: 1; transform: translateY(0); }\n}`,
    'Defina @keyframes girar com rotate(0deg) a rotate(360deg). Aplique animation: girar 0.8s linear infinite no .spinner.',
    chk('Qual o papel de "infinite" em animation: girar 1s linear infinite?',['A animação dura infinitos segundos','A animação se repete indefinidamente','A animação não tem direção','A animação é muito rápida'],1,'"infinite" é o valor do parâmetro iteration-count da animation. Faz a animação se repetir para sempre. Você pode usar um número (animation: nome 1s ease 3 = repete 3 vezes).'),
    'Você cria animações com @keyframes! Spinners, pulsações, entradas dramáticas, efeitos de texto — tudo isso é @keyframes. Você agora tem o poder de dar vida a qualquer elemento da página.',
    'c60','Crie @keyframes fadeInUp com opacity: 0 e translateY(30px) no from, e opacity: 1 e translateY(0) no to. Aplique em .card com animation: fadeInUp 0.6s ease-out forwards.',
    '@keyframes define a coreografia. animation: aplica no elemento com nome, duração, timing e iterações.',
    'animation-fill-mode: forwards mantém o estado final após a animação terminar.',
    'Código:\n@keyframes fadeInUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }\n.card { animation: fadeInUp 0.6s ease-out forwards; }'
  ),
];

// ─── MÓDULO 11 — Projeto Final ────────────────────────────────────────────────
const mod11: LessonInput[] = [

  mkLesson('Projeto Final: Planejamento','html',1,'Planejamento e wireframe do portfólio',
    `<!DOCTYPE html>\n<html lang="pt-BR">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Meu Portfólio</title>\n</head>\n<body>\n  <!-- Planeje sua estrutura aqui -->\n  <!-- header, main com sections, footer -->\n</body>\n</html>`,
    `function v(o,c){var l=c.toLowerCase();return l.includes('<header')&&l.includes('<main')&&l.includes('<footer');}v;`,
    'Você chegou ao projeto final! Agora é hora de usar TUDO que aprendeu para construir um portfólio pessoal — a peça mais importante do seu currículo como desenvolvedor.',
    'O que vamos construir',
    'Um site de portfólio com: navbar fixa, seção hero fullscreen, seção de projetos em Grid, seção de habilidades em Flexbox, formulário de contato e footer. Responsivo, animado e acessível.',
    `<!-- Estrutura planejada: -->\n<header>  <!-- navbar fixa -->\n<main>\n  <section id="hero">      <!-- tela cheia -->\n  <section id="projetos">  <!-- grade de cards -->\n  <section id="sobre">     <!-- sobre você -->\n  <section id="contato">   <!-- formulário -->\n</main>\n<footer>  <!-- copyright -->\n`,
    'Princípio da separação',
    'Um projeto profissional sempre separa estrutura (HTML), estilo (CSS) e comportamento (JavaScript). Nesse projeto, você terá um index.html e um style.css separados — tudo que você aprendeu no módulo de CSS Externo.',
    `/* Estrutura de arquivos: */\n/* portfólio/\n     index.html\n     style.css (importado via link)\n     img/ (fotos e ícones) */`,
    'No editor, esboce a estrutura HTML do portfólio com header, main (com 4 sections) e footer. Use comentários para identificar cada seção.',
    chk('Qual o primeiro passo ao construir qualquer site profissional?',['Escrever todo o CSS','Planejar a estrutura e as seções antes de codificar','Escolher as cores','Publicar o site'],1,'Planejar antes de codificar evita retrabalho. Um wireframe (mesmo que simples, em papel ou comentários) define quantas seções existem, quais elementos cada uma tem e como elas se conectam.'),
    'Você está planejando seu portfólio! Ter a estrutura HTML clara antes de aplicar CSS é o hábito que separa devs organizados de devs que refatoram código o dia inteiro.',
    'c61','Monte a estrutura HTML completa com: <header>, <main> com sections #hero, #projetos, #sobre e #contato, e <footer>.',
    'Use tags semânticas: <header>, <main>, <section>, <footer>. Cada section recebe um id para ser linkada na navbar.',
    'Adicione comentários para identificar cada seção: <!-- SEÇÃO: HERO -->.',
    'Código:\n<header>...</header>\n<main>\n  <section id="hero">...</section>\n  <section id="projetos">...</section>\n  <section id="sobre">...</section>\n  <section id="contato">...</section>\n</main>\n<footer>...</footer>'
  ),

  mkLesson('Projeto Final: Construção Base','css',2,'CSS base: navbar, hero e tipografia',
    `/* ===== RESET E BASE ===== */\n* {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}\n\n/* Adicione: variáveis CSS, body, navbar e hero */`,
    `function v(o,c){return c.includes('--')&&c.includes(':root')&&c.includes('position: fixed');}v;`,
    'Com a estrutura HTML pronta, é hora do CSS. Vamos começar pelas bases: variáveis CSS para o tema de cores, reset, tipografia e a navbar fixa.',
    'Variáveis CSS: o sistema de design',
    'CSS custom properties (variáveis) são declaradas com -- e usadas com var(). Centralize sua paleta de cores em :root para mudar o tema inteiro alterando apenas um lugar.',
    `:root {\n  --color-primary: #7c3aed;\n  --color-bg: #0f172a;\n  --color-surface: #1e293b;\n  --color-text: #f8fafc;\n  --font-main: 'Inter', sans-serif;\n  --radius: 12px;\n  --shadow: 0 4px 20px rgba(0,0,0,0.3);\n}`,
    'Navbar fixa com Flexbox',
    'A navbar usa position: fixed + z-index alto + display: flex com justify-content: space-between. Adicione backdrop-filter: blur() para o efeito glassmorphism moderno.',
    `.navbar {\n  position: fixed;\n  top: 0; left: 0; right: 0;\n  z-index: 100;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  padding: 0 5%;\n  height: 64px;\n  background: rgba(15,23,42,0.8);\n  backdrop-filter: blur(12px);\n}`,
    'Crie as variáveis CSS em :root com paleta de cores. Estilize a navbar com position: fixed e Flexbox. Adicione o hero fullscreen com Grid ou Flexbox.',
    chk('O que são CSS custom properties (variáveis)?',['Propriedades disponíveis só em Chrome','Valores reutilizáveis declarados com -- e usados com var()','Animações automáticas','Atalhos para propriedades longas'],1,'Variáveis CSS (custom properties) são declaradas com -- (ex: --cor-primaria: #7c3aed) e usadas com var(--cor-primaria). Centralize seu sistema de design em :root para manutenção fácil.'),
    'Você criou a base do portfólio! Variáveis CSS, reset e navbar fixa são o fundamento de qualquer projeto profissional moderno.',
    'c62','Declare variáveis em :root para cores e fontes. Crie .navbar com position: fixed, display: flex e z-index: 100. Crie .hero com min-height: 100vh e display: flex centralizado.',
    ':root { --variavel: valor; } declara. var(--variavel) usa.',
    'Navbar: position: fixed + top:0 + left:0 + right:0 + z-index alto.',
    'Código:\n:root { --primary: #7c3aed; --bg: #0f172a; }\n.navbar { position: fixed; top:0; left:0; right:0; z-index:100; display:flex; justify-content:space-between; align-items:center; height:64px; }'
  ),

  mkLesson('Projeto Final: Seções e Cards','css',3,'CSS avançado: Grid, cards e hover',
    `/* Seção de projetos com Grid */\n.projetos {\n  padding: 80px 5%;\n}\n.projetos-grid {\n  /* adicione Grid aqui */\n}\n.card-projeto {\n  /* adicione estilos de card */\n}`,
    `function v(o,c){return c.includes('display: grid')&&c.includes('border-radius:')&&c.includes(':hover');}v;`,
    'Hora de construir a seção de projetos — o coração do portfólio. Cards em Grid responsivo com hover, sombras e animações de entrada.',
    'Grid responsivo de projetos',
    'Use repeat(auto-fill, minmax(280px, 1fr)) para criar um grid que se adapta automaticamente. Cards que cabem na tela ficam lado a lado; numa tela menor, empilham. Sem media query.',
    `.projetos-grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));\n  gap: 24px;\n}`,
    'Cards com hover profissional',
    'Cards de portfólio têm: overflow: hidden (para a imagem não vazar), transition (para hover suave), transform: translateY(-8px) e box-shadow maiores no hover. Adicione @keyframes para animar a entrada.',
    `.card-projeto {\n  border-radius: 12px;\n  overflow: hidden;\n  transition: transform 0.3s ease, box-shadow 0.3s ease;\n}\n.card-projeto:hover {\n  transform: translateY(-8px);\n  box-shadow: 0 20px 40px rgba(0,0,0,0.3);\n}`,
    'Construa .projetos-grid com Grid auto-fill. Estilize .card-projeto com border-radius, overflow: hidden e hover com translateY e sombra.',
    chk('Por que overflow: hidden é importante num card com imagem?',['É obrigatório pelo CSS Grid','Evita que a imagem "vaze" para fora do border-radius do card','Esconde o texto','Melhora performance'],1,'border-radius cria cantos arredondados no contêiner, mas as imagens filhas (que são retangulares) ignoram isso. overflow: hidden recorta tudo que sai dos limites do card, incluindo os cantos da imagem.'),
    'Você construiu a seção de projetos! Grid auto-fill + cards com hover é o padrão que você vai ver em todo portfólio e página de produtos profissional.',
    'c63','Crie .projetos-grid com display: grid, auto-fill minmax(280px, 1fr), gap: 24px. Crie .card com border-radius: 12px, overflow: hidden, transition: all 0.3s ease e hover com translateY(-8px).',
    'repeat(auto-fill, minmax(280px, 1fr)) = cria automaticamente o número de colunas que cabem com mínimo de 280px.',
    'overflow: hidden + border-radius = imagem recortada nos cantos do card.',
    'Código:\n.projetos-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 24px; }\n.card { border-radius: 12px; overflow: hidden; transition: all 0.3s ease; }\n.card:hover { transform: translateY(-8px); }'
  ),

  mkLesson('Projeto Final: Responsividade','css',4,'Media queries no portfólio',
    `/* Mobile first base styles */\n.navbar-links {\n  display: none; /* oculto em mobile */\n}\n.hero h1 {\n  font-size: 2.5rem;\n}\n\n/* Adicione media queries para tablet e desktop */\n`,
    `function v(o,c){return c.includes('@media')&&c.includes('min-width')&&c.includes('{');}v;`,
    'O portfólio fica lindo no desktop — mas 60% dos visitantes estão no celular. Media queries transformam o site para funcionar perfeitamente em qualquer tela.',
    'Abordagem mobile-first',
    'Estilos base (sem @media) = mobile. @media (min-width: 768px) adiciona tablet. @media (min-width: 1024px) adiciona desktop. Do mais simples para o mais complexo — performance e manutenção melhores.',
    `/* Mobile (sem @media): */\n.hero h1 { font-size: 2.5rem; }\n.navbar-links { display: none; }\n\n/* Tablet: */\n@media (min-width: 768px) {\n  .hero h1 { font-size: 3.5rem; }\n}\n\n/* Desktop: */\n@media (min-width: 1024px) {\n  .navbar-links { display: flex; }\n  .hero h1 { font-size: 5rem; }\n}`,
    'O truque do menu hambúrguer',
    'Em mobile, o menu de links fica oculto (display: none). Um botão hambúrguer (☰) aparece. JavaScript adiciona uma classe ao clicar. CSS mostra o menu quando a classe está presente — mas você já pode preparar o CSS.',
    `/* Menu mobile: */\n.navbar-menu {\n  display: none;\n  position: fixed;\n  /* ... */\n}\n.navbar-menu.aberto {\n  display: flex;\n  flex-direction: column;\n}`,
    'Adicione media queries para 768px (ajusta tipografia, muda grid para 2 colunas) e 1024px (mostra navbar-links, aumenta hero).',
    chk('Por que mobile-first é melhor que desktop-first?',['O CSS mobile carrega mais rápido','Você começa pelo caso mais simples e adiciona complexidade progressivamente; performance e manutenção melhores','Mobile-first usa menos code','Desktop-first não funciona mais'],1,'Mobile-first: começa simples, adiciona. Desktop-first: começa complexo, remove. Adicionar é mais fácil e menos propenso a erros. Além disso, o CSS mobile é carregado por todos os dispositivos — fazer ele leve primeiro é boa prática de performance.'),
    'Você aplica responsividade no portfólio! Um site que funciona em mobile, tablet e desktop é o padrão mínimo do mercado. Você acabou de atingir isso.',
    'c64','Escreva media queries: (min-width: 768px) para aumentar tipografia e (min-width: 1024px) para mostrar navbar-links e aumentar ainda mais os títulos.',
    'Mobile: sem @media. Tablet: @media (min-width: 768px). Desktop: @media (min-width: 1024px).',
    'Em cada breakpoint, ajuste font-size, display de elementos ocultos e número de colunas do Grid.',
    'Código:\n@media (min-width: 768px) { .hero h1 { font-size: 3.5rem; } }\n@media (min-width: 1024px) { .navbar-links { display: flex; } .hero h1 { font-size: 5rem; } }'
  ),

  mkLesson('Projeto Final: Projeto Completo','css',5,'Revisão final e boas práticas',
    `/* ===== REVISÃO FINAL ===== */\n/* Adicione: animações de entrada, polish final, comentários */\n\n@keyframes fadeInUp {\n  /* complete a animação */\n}\n\n.hero-conteudo {\n  animation: /* complete */;\n}`,
    `function v(o,c){return c.includes('@keyframes')&&c.includes('animation:')&&c.includes('/*');}v;`,
    'Você chegou à aula final! Hora de polir o portfólio com animações de entrada, revisão de acessibilidade e boas práticas que diferenciam código profissional de amador.',
    'Animações de entrada: o toque final',
    'Animações de entrada (fade in, slide up) quando a página carrega tornam o site memorável. Use @keyframes + animation com animation-delay para criar uma sequência de elementos aparecendo.',
    `@keyframes fadeInUp {\n  from { opacity: 0; transform: translateY(30px); }\n  to   { opacity: 1; transform: translateY(0); }\n}\n.hero-titulo  { animation: fadeInUp 0.6s ease-out 0.1s both; }\n.hero-subtitulo { animation: fadeInUp 0.6s ease-out 0.3s both; }\n.hero-botao   { animation: fadeInUp 0.6s ease-out 0.5s both; }`,
    'Boas práticas: código CSS profissional',
    'Use comentários para separar seções. Organize o CSS na mesma ordem do HTML. Use variáveis CSS para todos os valores repetidos. Evite especificidade alta desnecessária. Prefira classes a IDs.',
    `/* ===== NAVBAR ===== */\n/* ===== HERO ===== */\n/* ===== PROJETOS ===== */\n/* ===== SOBRE ===== */\n/* ===== CONTATO ===== */\n/* ===== FOOTER ===== */\n/* ===== MEDIA QUERIES ===== */`,
    'Complete o @keyframes fadeInUp e aplique com animation-delay sequencial nos elementos do hero. Adicione comentários organizando o CSS por seção.',
    chk('O que animation-delay faz?',['Reduz a velocidade da animação','Atrasa o início da animação pelo tempo especificado','Pausa a animação no meio','Define o número de repetições'],1,'animation-delay define quanto tempo esperar antes de iniciar a animação. Usados em sequência (0.1s, 0.3s, 0.5s), criam um efeito elegante de elementos aparecendo um após o outro.'),
    '🎉 Parabéns! Você completou o curso de CSS do NeuroCode! De variáveis CSS a Grid, de Flexbox a @keyframes — você agora tem as habilidades para construir qualquer interface moderna. O próximo passo é JavaScript!',
    'c65','Complete @keyframes fadeInUp com opacity e translateY. Aplique com animation-delay de 0.1s, 0.3s e 0.5s nos três elementos principais do hero.',
    '@keyframes define de/para. animation: nome duração timing delay fill-mode aplica no elemento.',
    'animation-fill-mode: both = mantém estado inicial até começar E estado final ao terminar.',
    'Código:\n@keyframes fadeInUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }\n.titulo { animation: fadeInUp 0.6s ease-out 0.1s both; }\n.subtitulo { animation: fadeInUp 0.6s ease-out 0.3s both; }'
  ),
];

// ─── Exportação ────────────────────────────────────────────────────────────────
export const cssPart2Modules: ModuleInput[] = [
  {
    title: 'Módulo 7: Posicionamento',
    description: 'Controle a posição de elementos com relative, absolute, fixed, sticky e z-index.',
    order: 7,
    lessons: mod7,
  },
  {
    title: 'Módulo 8: CSS Grid',
    description: 'Construa layouts bidimensionais profissionais com CSS Grid.',
    order: 8,
    lessons: mod8,
  },
  {
    title: 'Módulo 9: Responsividade',
    description: 'Unidades relativas e media queries para sites que funcionam em qualquer tela.',
    order: 9,
    lessons: mod9,
  },
  {
    title: 'Módulo 10: Animações',
    description: 'Transitions, transforms e keyframes para interfaces animadas e profissionais.',
    order: 10,
    lessons: mod10,
  },
  {
    title: 'Módulo 11: Projeto Final',
    description: 'Construa um portfólio profissional aplicando tudo que aprendeu.',
    order: 11,
    lessons: mod11,
  },
];
