/**
 * seedCSSPart1.ts — Módulos 1 a 6 do Curso CSS (33 aulas)
 * NeuroCode · Metodologia ARPERC · lesson_rules.md
 */

export type LessonInput = {
  title: string;
  language: string;
  order: number;
  codeTemplate: string;
  validationLogic: string;
  content: string;
};

export type ModuleInput = {
  title: string;
  description: string;
  order: number;
  lessons: LessonInput[];
};

// ─── helpers ──────────────────────────────────────────────────────────────────
const chk = (q: string, opts: string[], ci: number, exp: string) => ({
  question: q, options: opts, correctIndex: ci, explanation: exp
});

const blocks = (
  hookTxt: string,
  exATitle: string, exATxt: string, exACode: string,
  exBTitle: string, exBTxt: string, exBCode: string,
  pracTxt: string,
  checkpoint: ReturnType<typeof chk>,
  rewardTxt: string,
  prefix: string
) => ([
  { id: `hook-${prefix}`,   type: 'hook',       content: hookTxt },
  { id: `exp-${prefix}a`,   type: 'explain',    title: exATitle,  content: exATxt,  code: exACode },
  { id: `exp-${prefix}b`,   type: 'explain',    title: exBTitle,  content: exBTxt,  code: exBCode },
  { id: `prac-${prefix}`,   type: 'practice',   content: pracTxt },
  { id: `chk-${prefix}`,    type: 'checkpoint', content: 'Verificação rápida:', checkpoint },
  { id: `rew-${prefix}`,    type: 'reward',     content: rewardTxt },
]);

const mkLesson = (
  title: string, language: string, order: number,
  concept: string, template: string, validate: string,
  hookTxt: string,
  exATitle: string, exATxt: string, exACode: string,
  exBTitle: string, exBTxt: string, exBCode: string,
  pracTxt: string, checkpoint: ReturnType<typeof chk>, rewardTxt: string,
  prefix: string,
  chalInstr: string, h1: string, h2: string, h3: string
): LessonInput => ({
  title, language, order,
  codeTemplate: template,
  validationLogic: validate,
  content: JSON.stringify({
    title, concept,
    blocks: blocks(hookTxt, exATitle, exATxt, exACode, exBTitle, exBTxt, exBCode, pracTxt, checkpoint, rewardTxt, prefix),
    challenge: { instruction: chalInstr, hints: [h1, h2, h3] as [string,string,string] }
  })
});

// ─── MÓDULO 1 — Introdução ao CSS ─────────────────────────────────────────────
const mod1: LessonInput[] = [

  mkLesson('O que é CSS','css',1,'CSS: Cascading Style Sheets',
    `/* Escreva sua primeira regra CSS */\nh1 {\n  \n}`,
    `function v(o,c){return c.includes('{')&&c.includes(':')&&c.includes(';');}v;`,
    'Imagine que o HTML é o esqueleto de uma página e o CSS é a roupa, maquiagem e decoração. Sem CSS, a internet seria texto preto em fundo branco.',
    'O que é CSS?',
    'CSS (Cascading Style Sheets) é a linguagem que controla a aparência visual do HTML. Com ela você define cores, fontes, tamanhos e posicionamento de qualquer elemento.',
    `h1 {\n  color: blue;\n  font-size: 32px;\n}`,
    'Como o CSS funciona',
    'O CSS funciona assim: você seleciona um elemento HTML (como h1), abre chaves { } e escreve pares de propriedade: valor; Cada par é uma instrução visual.',
    `p {\n  color: red;\n  background-color: lightyellow;\n}`,
    'No editor, escreva uma regra para h1 com qualquer cor. Use: h1 { color: nomeDaCor; }',
    chk('O que CSS significa?',['Creative Style Sheets','Cascading Style Sheets','Colorful Script Styles','Computer Style System'],1,'CSS = Cascading Style Sheets (Folhas de Estilo em Cascata). "Cascading" se refere à hierarquia de regras — regras mais específicas sobrescrevem as gerais.'),
    'Você entendeu o papel do CSS! HTML estrutura, CSS estiliza — essa dupla está em todo projeto web.',
    'c1','Escreva uma regra CSS que deixe o h1 na cor "purple".',
    'O seletor é h1, seguido de { }.',
    'A propriedade de cor de texto é "color" e o valor é "purple".',
    'Código completo: h1 { color: purple; }'
  ),

  mkLesson('CSS Inline','html',2,'CSS Inline: atributo style=""',
    `<!-- Adicione estilo diretamente no elemento -->\n<p>Este parágrafo precisa de cor!</p>\n`,
    `function v(o,c){return c.includes('style=')&&c.includes(':');}v;`,
    'A forma mais imediata de aplicar CSS é escrever estilos diretamente no elemento HTML — como colocar uma etiqueta de roupa direto na peça.',
    'O atributo style=""',
    'Qualquer tag HTML aceita o atributo style="". Dentro das aspas, você escreve as regras CSS separadas por ponto-e-vírgula. O CSS se aplica apenas àquele elemento específico.',
    `<p style="color: red; font-size: 20px;">\n  Texto vermelho e maior!\n</p>`,
    'Quando NÃO usar CSS inline',
    'CSS inline tem uma desvantagem: você precisa repetir o código em cada elemento. É útil para testes rápidos, mas para projetos reais, use CSS interno ou externo.',
    `<!-- Ruim para manutenção: -->\n<p style="color: blue;">Parágrafo 1</p>\n<p style="color: blue;">Parágrafo 2</p>`,
    'Adicione style="" no elemento <p> do editor para deixar o texto vermelho e em negrito (font-weight: bold).',
    chk('Onde fica o CSS inline?',['Em um arquivo .css separado','Dentro da tag <style>','Diretamente no atributo style="" do elemento','No arquivo JavaScript'],2,'CSS inline fica no atributo style="" dentro da tag HTML. É o mais específico e sobrescreve todas as outras formas de CSS.'),
    'Você aplicou CSS inline! Agora sabe a forma mais direta (e poderosa em especificidade) de estilizar um elemento.',
    'c2','Faça o parágrafo exibir o texto em cor "green" e tamanho "font-size: 18px" usando CSS inline.',
    'Adicione o atributo style="" dentro da tag <p>.',
    'Dentro de style="", escreva as propriedades separadas por ponto-e-vírgula: color: green; font-size: 18px;',
    'Código: <p style="color: green; font-size: 18px;">Seu texto</p>'
  ),

  mkLesson('CSS Interno','html',3,'CSS Interno: tag <style>',
    `<!DOCTYPE html>\n<html>\n  <head>\n    <!-- Adicione a tag <style> aqui -->\n  </head>\n  <body>\n    <h1>Título</h1>\n    <p>Parágrafo de teste.</p>\n  </body>\n</html>\n`,
    `function v(o,c){return c.includes('<style>')&&c.includes('</style>')&&c.includes('{');}v;`,
    'E se você quiser estilizar todos os parágrafos de uma vez, sem repetir style="" em cada um? O CSS interno resolve isso com uma única tag <style>.',
    'A tag <style> no <head>',
    'Você coloca uma tag <style> dentro do <head> do HTML. Tudo que estiver dentro dela é CSS puro, aplicado a toda a página. Uma regra controla todos os elementos do mesmo tipo.',
    `<head>\n  <style>\n    h1 {\n      color: navy;\n      font-size: 36px;\n    }\n    p {\n      color: gray;\n    }\n  </style>\n</head>`,
    'Vantagem e limitação',
    'CSS interno é ótimo para páginas únicas: você tem estilos e HTML no mesmo arquivo. A limitação é que o estilo não pode ser reutilizado em outras páginas — para isso, existe o CSS externo.',
    `<!-- Tudo dentro de <style> se aplica à página inteira -->\n<style>\n  body {\n    background-color: #f0f0f0;\n  }\n</style>`,
    'Adicione um bloco <style> no <head> do template e estilize o h1 com cor azul e o p com cor cinza.',
    chk('Onde a tag <style> deve ficar?',['No <body>, antes do conteúdo','No <head> do HTML','No <footer>','Em qualquer lugar'],1,'A tag <style> deve ficar no <head> do HTML. Isso garante que os estilos sejam carregados antes do conteúdo aparecer, evitando "flash" visual.'),
    'Agora você controla múltiplos elementos com uma única regra! Isso é muito mais eficiente do que CSS inline.',
    'c3','Adicione um <style> no <head> e deixe o h1 com color: darkblue e o p com color: #555.',
    'A tag <style> vai dentro de <head>. Dentro dela, escreva CSS normal.',
    'Escreva h1 { } e p { } separados dentro do <style>.',
    'Código:\n<style>\n  h1 { color: darkblue; }\n  p { color: #555; }\n</style>'
  ),

  mkLesson('CSS Externo','css',4,'CSS Externo: arquivo .css separado',
    `/* style.css — seu arquivo de estilos */\nbody {\n  \n}\n`,
    `function v(o,c){return c.includes('{')&&c.includes(':')&&c.includes(';');}v;`,
    'Imagine um guarda-roupa centralizado: em vez de ter roupas espalhadas por toda a casa, tudo fica organizado em um só lugar. CSS externo é isso — um arquivo de estilos que serve múltiplas páginas.',
    'Como funciona o CSS externo',
    'Você cria um arquivo separado com extensão .css (ex: style.css) e o conecta ao HTML com uma tag <link>. Todas as páginas que usarem esse <link> compartilharão os mesmos estilos automaticamente.',
    `<!-- No HTML, dentro do <head>: -->\n<link rel="stylesheet" href="style.css">\n\n/* No arquivo style.css: */\nh1 {\n  color: darkblue;\n}`,
    'Por que é a forma preferida',
    'CSS externo é a forma padrão em projetos profissionais: um arquivo de 500 linhas de CSS serve 100 páginas HTML. Se você mudar a cor principal, muda em um lugar e todas as páginas se atualizam.',
    `<!-- Conectar um arquivo CSS externo: -->\n<link rel="stylesheet" href="./estilos/style.css">\n<link rel="stylesheet" href="./estilos/reset.css">`,
    'No editor (que simula um arquivo style.css), escreva regras para body com background-color e para h1 com color.',
    chk('Qual tag conecta um CSS externo ao HTML?',['<css>','<style src="">','<link rel="stylesheet" href="">','<import css="">'],2,'A tag <link rel="stylesheet" href="caminho"> conecta o arquivo CSS ao HTML. Ela fica no <head> e deve ter rel="stylesheet" para o navegador saber que é um arquivo de estilos.'),
    'Você entende os três métodos de aplicar CSS: inline, interno e externo. Em projetos reais, usaremos sempre o externo!',
    'c4','No arquivo CSS do editor, escreva uma regra para body com background-color: #1a1a2e e para h1 com color: white.',
    'O editor simula um arquivo .css. Escreva CSS puro — sem tags HTML.',
    'Escreva body { } e dentro coloque a propriedade background-color com o valor.',
    'Código:\nbody { background-color: #1a1a2e; }\nh1 { color: white; }'
  ),

  mkLesson('Seletores Básicos','css',5,'Seletores CSS: tag, classe e ID',
    `/* Experimente diferentes seletores */\n`,
    `function v(o,c){return c.includes('{')&&c.includes(':');}v;`,
    'Seletores são como ponteiros: você aponta para o elemento certo antes de estilizá-lo. Existem três tipos básicos — e cada um tem um poder diferente.',
    'Seletor de tag',
    'O seletor de tag seleciona TODOS os elementos daquele tipo. Escreva o nome da tag e abre chaves. É o mais simples e o menos específico.',
    `h1 { color: blue; }    /* todo h1 da página */\np  { color: gray; }    /* todo p da página */\na  { color: purple; }  /* todo link da página */`,
    'Seletores de classe e ID',
    'O seletor de classe começa com ponto (.nomeClasse) e seleciona elementos com aquele class="" no HTML. O seletor de ID começa com # (#nomeId) e seleciona um elemento único com id="".',
    `.destaque { background-color: yellow; } /* class="destaque" */\n#logo     { font-size: 48px; }          /* id="logo" */`,
    'No editor, escreva três regras: uma para p (tag), uma para .importante (classe), e uma para #titulo (id).',
    chk('Como selecionar todos os elementos <p> da página?',['#p { }','.p { }','p { }','<p> { }'],2,'O seletor de tag usa apenas o nome da tag sem nenhum prefixo. p { } seleciona todos os parágrafos. .p { } seria uma classe chamada "p" (diferente!).'),
    'Você domina os três seletores fundamentais! Com tag, classe e ID você pode estilizar qualquer elemento de qualquer forma.',
    'c5','Escreva: seletor de tag h2 com color red, seletor de classe .card com background-color white, e seletor de ID #hero com font-size 48px.',
    'Lembre: tag → nome da tag, classe → .nome, ID → #nome.',
    'Cada seletor tem seu bloco { } com as propriedades dentro.',
    'Código:\nh2 { color: red; }\n.card { background-color: white; }\n#hero { font-size: 48px; }'
  ),
];

// ─── MÓDULO 2 — Aparência ──────────────────────────────────────────────────────
const mod2: LessonInput[] = [

  mkLesson('Cor do Texto','css',1,'Propriedade color',
    `h1 {\n  /* defina a cor do texto aqui */\n}\np {\n  \n}`,
    `function v(o,c){return c.includes('color:')&&!c.includes('background-color');}v;`,
    'A propriedade mais usada em CSS é a color. Em minutos você vai transformar texto monótono em algo com personalidade.',
    'Formatos de cor',
    'O CSS aceita cores em quatro formatos: nome (red, blue), hexadecimal (#FF0000), RGB (rgb(255,0,0)) e HSL (hsl(0,100%,50%)). Todos funcionam — escolha o que for mais natural.',
    `h1 { color: tomato; }           /* nome */\nh2 { color: #3498db; }          /* hex */\np  { color: rgb(46, 204, 113); } /* rgb */`,
    'Cores modernas com HSL',
    'HSL (Hue, Saturation, Lightness) é o formato mais intuitivo: hue é a matiz (0-360°), saturation é a vivacidade (0-100%) e lightness é o brilho (0-100%). Ótimo para criar paletas.',
    `h1 {\n  color: hsl(220, 80%, 50%); /* azul vibrante */\n}\np {\n  color: hsl(220, 10%, 40%); /* cinza-azulado */\n}`,
    'Aplique color em h1 e p no editor. Experimente hex (#8b5cf6) para o h1 e rgb para o p.',
    chk('Qual propriedade CSS define a cor do TEXTO?',['text-color','font-color','color','background'],2,'"color" é a propriedade que define a cor do texto de um elemento. "background-color" define o fundo. "text-color" e "font-color" não existem em CSS.'),
    'Você controla cores em quatro formatos! Desenvolvedores profissionais preferem hex ou HSL para paletas mais precisas.',
    'c6','Deixe o h1 com color: #8b5cf6 (roxo) e o p com color: rgb(15, 23, 42) (azul escuro).',
    'A propriedade é "color" (sem "text-" na frente) e vai dentro das chaves.',
    'Para hex, use # seguido de 6 dígitos. Para RGB, use rgb(r,g,b) com valores de 0 a 255.',
    'Código:\nh1 { color: #8b5cf6; }\np { color: rgb(15, 23, 42); }'
  ),

  mkLesson('Cor de Fundo','css',2,'Propriedade background-color',
    `body {\n  /* cor de fundo aqui */\n}\n.card {\n  \n}`,
    `function v(o,c){return c.includes('background-color:');}v;`,
    'Cor de texto é metade da história visual. A cor de fundo transforma um elemento de invisível para presente — como ligar a luz de um quarto escuro.',
    'background-color',
    'A propriedade background-color pinta o fundo do elemento. Funciona com os mesmos formatos de cor: nome, hex, rgb, hsl. O fundo ocupa toda a área do elemento, incluindo padding.',
    `body {\n  background-color: #0f172a; /* fundo escuro */\n}\nh1 {\n  background-color: #7c3aed; /* destaque roxo */\n}`,
    'Combinando com color',
    'O segredo do design é combinar color (texto) e background-color (fundo) com contraste adequado. Texto escuro em fundo claro, ou texto claro em fundo escuro — nunca cinza em cinza!',
    `.card {\n  background-color: white;\n  color: #1e293b;\n}\n.card-dark {\n  background-color: #1e293b;\n  color: white;\n}`,
    'Defina background-color no body (fundo da página) e em .card (um bloco específico). Experimente cores que contrastem bem.',
    chk('O que background-color define?',['A cor do texto','A cor de fundo do elemento','A imagem de fundo','A transparência'],1,'background-color define a cor sólida de fundo do elemento. Para imagens de fundo, existe a propriedade background-image. Para transparência, existe opacity.'),
    'Com color e background-color você já cria esquemas de cores completos. Isso é o coração do design visual!',
    'c7','Dê ao body background-color: #0f172a e ao .card background-color: #1e293b com color: white.',
    'Use background-color (com hífen) — não "bg-color" nem "background".',
    'Escreva o seletor, { } e dentro a propriedade background-color seguida de dois-pontos e o valor.',
    'Código:\nbody { background-color: #0f172a; }\n.card { background-color: #1e293b; color: white; }'
  ),

  mkLesson('Imagem de Fundo','css',3,'Propriedade background-image',
    `body {\n  /* adicione uma imagem de fundo */\n  min-height: 100vh;\n}`,
    `function v(o,c){return c.includes('background-image:')&&c.includes('url(');}v;`,
    'Uma cor sólida é bom. Uma textura ou imagem como fundo eleva o design a outro nível — como trocar o papel de parede de um quarto.',
    'background-image com url()',
    'A propriedade background-image usa a função url() para carregar uma imagem. O caminho pode ser uma URL externa ou um arquivo local. Por padrão, a imagem se repete em mosaico.',
    `body {\n  background-image: url('https://picsum.photos/800/600');\n  background-size: cover;    /* cobre toda a área */\n  background-position: center; /* centralizada */\n}`,
    'Propriedades complementares',
    'background-image raramente vem sozinha. Use background-size (cover, contain ou px) para o tamanho, background-repeat (no-repeat, repeat) para controlar repetição e background-position para posicionamento.',
    `section {\n  background-image: url('hero.jpg');\n  background-size: cover;\n  background-repeat: no-repeat;\n  background-position: center top;\n}`,
    'Use a URL de exemplo (https://picsum.photos/800/400) como background-image no body. Adicione background-size: cover e background-repeat: no-repeat.',
    chk('Qual função CSS carrega uma imagem?',['image()','src()','url()','load()'],2,'url() é a função CSS para referenciar arquivos externos — imagens, fontes, etc. Sempre use: background-image: url(\'caminho-da-imagem\');'),
    'Você adicionou imagens de fundo! background-image com background-size: cover é a combinação mais usada em seções de hero de sites modernos.',
    'c8','Use background-image com url(\'https://picsum.photos/1200/600\'), background-size: cover e background-position: center.',
    'background-image precisa de url(). Coloque o endereço entre aspas dentro dos parênteses.',
    'Adicione também background-size: cover para a imagem preencher todo o elemento.',
    'Código:\nbody {\n  background-image: url(\'https://picsum.photos/1200/600\');\n  background-size: cover;\n  background-position: center;\n}'
  ),

  mkLesson('Opacidade','css',4,'Propriedade opacity',
    `.elemento {\n  background-color: purple;\n  /* adicione opacity aqui */\n}`,
    `function v(o,c){return c.includes('opacity:');}v;`,
    'Efeitos de transparência dão profundidade ao design — como vidros foscos, sobreposições escurecidas ou elementos "fantasma". O CSS faz isso com a propriedade opacity.',
    'opacity: de 0 a 1',
    'opacity aceita valores de 0 (totalmente transparente) a 1 (totalmente opaco). Valores decimais criam semitransparência. Atenção: opacity afeta o elemento INTEIRO — texto, fundo e filhos.',
    `.overlay {\n  background-color: black;\n  opacity: 0.5; /* 50% transparente */\n}\n.fantasma {\n  opacity: 0.3; /* quase invisível */\n}`,
    'rgba — transparência só no fundo',
    'Se você quer transparência apenas na cor de fundo (sem afetar o texto), use rgba() no background-color. O quarto valor (alpha) vai de 0 a 1, igual ao opacity.',
    `.card {\n  /* Transparência só no fundo, texto fica opaco: */\n  background-color: rgba(0, 0, 0, 0.6);\n  color: white;\n}`,
    'Aplique opacity: 0.7 ao .elemento no editor. Depois tente rgba(128, 0, 128, 0.5) no background-color e veja a diferença.',
    chk('Qual a diferença entre opacity e rgba()?',['São idênticos','opacity afeta o elemento inteiro; rgba() afeta só a cor de fundo','opacity é mais rápido','rgba() não funciona em CSS moderno'],1,'opacity torna TODO o elemento transparente (texto, fundo, filhos). rgba() aplica transparência apenas à cor especificada. Use rgba() quando quiser fundo transparente mas texto nítido.'),
    'Você domina transparência em CSS! A combinação de overlay com rgba() é usada em cards de destaque, modals e banners em toda a web.',
    'c9','Crie um .overlay com background-color: rgba(0,0,0,0.6) e um .card com opacity: 0.8.',
    'Para o overlay, use rgba() no background-color — não opacity — para o texto permanecer legível.',
    'rgba(vermelho, verde, azul, alpha) — o quarto número é a transparência de 0 a 1.',
    'Código:\n.overlay { background-color: rgba(0,0,0,0.6); }\n.card { opacity: 0.8; }'
  ),

  mkLesson('Gradientes','css',5,'CSS Gradients: linear-gradient',
    `.hero {\n  /* crie um gradiente aqui */\n  height: 200px;\n}`,
    `function v(o,c){return c.includes('gradient');}v;`,
    'Gradientes são as transições suaves entre cores — como o pôr do sol ou as capas de álbuns modernos. São criados 100% com CSS, sem imagens.',
    'linear-gradient()',
    'A função linear-gradient() cria um gradiente linear. Você define a direção e as cores. A direção pode ser um ângulo (45deg) ou palavras como "to right", "to bottom".',
    `.hero {\n  background: linear-gradient(to right, #7c3aed, #2563eb);\n}\n.sunset {\n  background: linear-gradient(135deg, #f97316, #ec4899);\n}`,
    'Gradientes com múltiplas cores e paradas',
    'Você pode ter mais de duas cores e controlar onde cada uma começa (color stops). Gradientes também podem ser radiais com radial-gradient().',
    `.arcoiris {\n  background: linear-gradient(\n    to right,\n    #ef4444 0%,\n    #f97316 25%,\n    #eab308 50%,\n    #22c55e 75%,\n    #3b82f6 100%\n  );\n}`,
    'Crie um gradiente no .hero do editor. Use "to bottom right" como direção e duas cores de sua escolha.',
    chk('Qual propriedade recebe linear-gradient()?',['color','gradient','background ou background-image','fill'],2,'linear-gradient() é um valor da propriedade background (ou background-image). Nunca é uma propriedade separada: background: linear-gradient(...)'),
    'Você cria gradientes profissionais com CSS! Essa habilidade transforma qualquer elemento em algo visualmente atraente sem precisar de imagens.',
    'c10','Crie um gradiente diagonal (135deg) do roxo (#7c3aed) para o azul (#2563eb) no .hero.',
    'Use background: linear-gradient(ângulo, cor1, cor2).',
    'O ângulo 135deg faz o gradiente ir do canto superior esquerdo ao inferior direito.',
    'Código:\n.hero { background: linear-gradient(135deg, #7c3aed, #2563eb); }'
  ),
];

// ─── MÓDULO 3 — Texto ──────────────────────────────────────────────────────────
const mod3: LessonInput[] = [

  mkLesson('Família de Fonte','css',1,'Propriedade font-family',
    `body {\n  /* defina a família de fonte */\n}`,
    `function v(o,c){return c.includes('font-family:');}v;`,
    'A tipografia é a alma do design. A mesma frase em fontes diferentes transmite sensações completamente distintas — elegância, modernidade, seriedade ou diversão.',
    'font-family e fallbacks',
    'font-family define a fonte do texto. Sempre inclua fontes de fallback separadas por vírgula — o navegador usa a primeira disponível. A última deve ser uma família genérica (serif, sans-serif, monospace).',
    `body {\n  font-family: 'Inter', 'Roboto', sans-serif;\n}\ncode {\n  font-family: 'Fira Code', 'Courier New', monospace;\n}`,
    'Google Fonts',
    'Para usar fontes personalizadas, adicione um <link> do Google Fonts no HTML e então use font-family no CSS. É gratuito e tem centenas de opções.',
    `/* No HTML: */\n/* <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet"> */\n\n/* No CSS: */\nbody {\n  font-family: 'Inter', sans-serif;\n}`,
    'Defina font-family no body com "Arial", "Helvetica", sans-serif. Depois tente trocar a fonte e veja a diferença visual.',
    chk('Por que incluir fontes de fallback?',['Para ser mais rápido','Caso a fonte principal não esteja disponível no dispositivo do usuário','Para economizar memória','Por obrigação do W3C'],1,'Fontes precisam de fallback porque nem todo dispositivo tem todas as fontes instaladas. O navegador tenta cada fonte na lista e usa a primeira que encontrar.'),
    'Você controla tipografia com font-family! A escolha da fonte é uma das decisões de design mais importantes de qualquer projeto.',
    'c11','Defina no body: font-family com "Segoe UI", "Roboto", sans-serif. Em h1, use "Georgia", serif.',
    'A propriedade é font-family (com hífen). Fontes com espaço no nome ficam entre aspas.',
    'Separe as fontes por vírgula. A última deve ser serif, sans-serif ou monospace.',
    'Código:\nbody { font-family: "Segoe UI", "Roboto", sans-serif; }\nh1 { font-family: "Georgia", serif; }'
  ),

  mkLesson('Tamanho de Fonte','css',2,'Propriedade font-size',
    `h1 {\n  /* defina o tamanho da fonte */\n}\np {\n  \n}`,
    `function v(o,c){return c.includes('font-size:');}v;`,
    'Hierarquia visual começa com tamanho. Um título gigante e um corpo de texto menor guiam o olhar do leitor naturalmente — como manchetes de jornal.',
    'Unidades para font-size',
    'Você pode usar px (pixels fixos), rem (relativo ao tamanho base do documento), em (relativo ao elemento pai) ou % (percentual). Para responsividade, rem é o mais recomendado.',
    `h1 { font-size: 48px; }   /* pixels fixos */\nh2 { font-size: 2rem; }    /* 2x o tamanho base (32px se base=16px) */\np  { font-size: 1rem; }    /* tamanho base */\nsmall { font-size: 0.875rem; } /* um pouco menor */`,
    'Escala tipográfica',
    'Uma escala tipográfica é uma sequência harmônica de tamanhos. Uma regra prática: h1 ≈ 3rem, h2 ≈ 2rem, h3 ≈ 1.5rem, p ≈ 1rem. Isso cria hierarquia clara sem pular etapas.',
    `h1 { font-size: 3rem; }    /* ~48px */\nh2 { font-size: 2rem; }    /* ~32px */\nh3 { font-size: 1.5rem; }  /* ~24px */\np  { font-size: 1rem; }    /* ~16px */`,
    'Defina font-size no h1 (3rem) e no p (1rem) do editor. Observe a hierarquia visual criada.',
    chk('Qual unidade de font-size é mais indicada para sites responsivos?',['px','mm','rem','pt'],2,'rem (root em) é proporcional ao tamanho de fonte do elemento raiz (html). Quando o usuário aumenta o zoom do navegador, rem se ajusta automaticamente. px é fixo e não escala.'),
    'Você cria hierarquia tipográfica com font-size! Usar rem torna seu site mais acessível e responsivo.',
    'c12','Defina h1 com font-size: 3rem, h2 com 2rem, p com 1rem e small com 0.875rem.',
    'rem é proporcional ao tamanho base — geralmente 16px. Então 2rem = 32px.',
    'Use rem para todos. Escreva: seletor { font-size: valorrem; }',
    'Código:\nh1 { font-size: 3rem; }\nh2 { font-size: 2rem; }\np { font-size: 1rem; }\nsmall { font-size: 0.875rem; }'
  ),

  mkLesson('Peso da Fonte','css',3,'Propriedade font-weight',
    `p {\n  /* experimente font-weight */\n}\nstrong {\n  \n}`,
    `function v(o,c){return c.includes('font-weight:');}v;`,
    'Negrito não é apenas "mais grosso" — é ênfase. Um título em bold chama atenção. Um detalhe em 300 (thin) é refinado. O peso certo transmite a mensagem certa.',
    'Valores de font-weight',
    'font-weight aceita palavras-chave (normal = 400, bold = 700) ou números de 100 a 900 (em múltiplos de 100). Nem todas as fontes têm todos os pesos — depende dos arquivos disponíveis.',
    `h1 { font-weight: 900; }    /* ultra bold */\nh2 { font-weight: 700; }    /* bold padrão */\np  { font-weight: 400; }    /* normal */\nsmall { font-weight: 300; } /* leve */`,
    'font-weight com Google Fonts',
    'Ao importar fontes do Google Fonts, você escolhe quais pesos quer carregar. Usar um peso não importado fará o navegador substituir pelo mais próximo disponível.',
    `/* Google Fonts com múltiplos pesos: */\n/* ?family=Inter:wght@300;400;600;700;900 */\n\n.titulo { font-weight: 900; } /* Inter Black */\n.corpo  { font-weight: 400; } /* Inter Regular */`,
    'Aplique font-weight 900 no h1, 400 no p e 300 em um elemento small. Observe como o peso afeta a personalidade do texto.',
    chk('Qual o valor numérico equivalente a font-weight: bold?',['400','500','600','700'],3,'bold é equivalente a 700. normal é equivalente a 400. A escala vai de 100 (Thin) a 900 (Black), com 400 como padrão e 700 como bold padrão.'),
    'Você controla o peso das fontes! A escala 100-900 dá liberdade criativa para criar hierarquias visuais sofisticadas.',
    'c13','Defina h1 com font-weight: 800, p com font-weight: 400 e .subtitulo com font-weight: 300.',
    'font-weight aceita números de 100 a 900 ou palavras-chave como bold e normal.',
    'Lembre que nem todas as fontes têm todos os pesos. Trabalhos com Google Fonts dão mais controle.',
    'Código:\nh1 { font-weight: 800; }\np { font-weight: 400; }\n.subtitulo { font-weight: 300; }'
  ),

  mkLesson('Alinhamento de Texto','css',4,'Propriedade text-align',
    `h1 {\n  /* alinhe o texto */\n}\np {\n  \n}`,
    `function v(o,c){return c.includes('text-align:');}v;`,
    'Texto centralizado em títulos, texto justificado em artigos longos, texto à direita em preços — cada alinhamento tem um propósito e transmite uma intenção de design.',
    'Valores de text-align',
    'text-align aceita quatro valores principais: left (esquerda — padrão), right (direita), center (centro) e justify (justificado, como em livros). O alinhamento é aplicado ao bloco de texto.',
    `h1 { text-align: center; }   /* título centralizado */\np  { text-align: justify; }  /* parágrafos justificados */\n.preco { text-align: right; } /* preços à direita */`,
    'Quando usar cada alinhamento',
    'Center: títulos, callouts, botões. Justify: parágrafos longos (com cuidado — pode criar espaços desiguais). Right: números, preços, datas em tabelas. Left: padrão para texto corrido.',
    `.artigo p {\n  text-align: justify;\n  text-align-last: left; /* última linha à esquerda */\n}`,
    'Aplique text-align: center no h1 e text-align: justify no p do editor. Observe a diferença de leiturabilidade.',
    chk('Qual text-align distribui o texto igualmente pelas margens esquerda e direita?',['center','distribute','justify','even'],2,'text-align: justify estica o espaço entre palavras para alinhar simultaneamente à margem esquerda e direita — como em livros e jornais impressos.'),
    'Você controla alinhamento de texto! Essa propriedade simples muda completamente a aparência e legibilidade de qualquer página.',
    'c14','Centralize o h1, justifique o p e alinhe à direita um elemento .preco.',
    'A propriedade é text-align. Os valores são: left, right, center, justify.',
    'Escreva cada seletor com seu bloco { } e a propriedade text-align com o valor correto.',
    'Código:\nh1 { text-align: center; }\np { text-align: justify; }\n.preco { text-align: right; }'
  ),

  mkLesson('Decoração de Texto','css',5,'Propriedade text-decoration',
    `a {\n  /* remova o sublinhado padrão */\n}\n.destaque {\n  \n}`,
    `function v(o,c){return c.includes('text-decoration:');}v;`,
    'Links em azul sublinhado são o padrão do navegador — mas designs modernos removem ou personalizam essa decoração. Você tem controle total com text-decoration.',
    'Valores de text-decoration',
    'Os valores mais comuns são: none (remove decoração), underline (sublinhado), line-through (tachado — como preço riscado), overline (linha acima). Você pode combinar com cor e estilo.',
    `a { text-decoration: none; }           /* remove sublinhado de links */\n.riscado { text-decoration: line-through; } /* preço antigo */\n.titulo  { text-decoration: underline dotted; } /* sublinhado pontilhado */`,
    'Decorações avançadas',
    'text-decoration é um shorthand para: text-decoration-line, text-decoration-color e text-decoration-style. Você pode sublinhar com cor e estilo específicos.',
    `.preco-antigo {\n  text-decoration: line-through;\n  text-decoration-color: red;\n  opacity: 0.6;\n}`,
    'Remova o sublinhado padrão de a com text-decoration: none. Depois adicione text-decoration: line-through no .promocao.',
    chk('Como remover o sublinhado padrão de links?',['underline: none','text-decoration: no-line','text-decoration: none','link-style: clean'],2,'text-decoration: none remove qualquer decoração de texto, incluindo o sublinhado padrão dos links. É uma das regras CSS mais usadas em todo projeto web.'),
    'Você controla decorações de texto! Remover sublinhado de links e adicionar line-through em promoções são usos clássicos em todo e-commerce.',
    'c15','Remova o sublinhado do a com text-decoration: none. No .promocao, adicione text-decoration: line-through.',
    'text-decoration: none remove qualquer decoração existente.',
    'line-through "risca" o texto — muito usado para preços em promoção.',
    'Código:\na { text-decoration: none; }\n.promocao { text-decoration: line-through; }'
  ),

  mkLesson('Altura de Linha','css',6,'Propriedade line-height',
    `p {\n  font-size: 1rem;\n  /* adicione line-height */\n}`,
    `function v(o,c){return c.includes('line-height:');}v;`,
    'Texto muito comprimido cansa os olhos. Texto muito espaçado perde a coerência. line-height é o ajuste fino que torna a leitura confortável — especialmente importante para TDAH e dislexia.',
    'line-height: a unidade sem unidade',
    'line-height aceita um número sem unidade (ex: 1.6) — que é multiplicado pelo font-size atual. É a forma recomendada. Usar 1.6 em um texto de 16px cria espaçamento de 25.6px entre linhas.',
    `p {\n  font-size: 1rem;   /* 16px */\n  line-height: 1.6;  /* 25.6px de altura de linha */\n}\n\n.compact {\n  line-height: 1.2;  /* mais comprimido */\n}`,
    'Por que importa para acessibilidade',
    'A WCAG (diretrizes de acessibilidade web) recomenda line-height de pelo menos 1.5 para texto corrido. Para pessoas com dislexia, 1.8 ou mais pode fazer uma diferença enorme na leitura.',
    `.artigo {\n  font-size: 1.1rem;\n  line-height: 1.8; /* muito confortável */\n}\n\n.codigo {\n  font-family: monospace;\n  line-height: 1.5;\n}`,
    'Aplique line-height: 1.6 no parágrafo do editor. Depois tente 1.2 e 2.0 para sentir a diferença.',
    chk('Qual o valor recomendado de line-height para leiturabilidade?',['0.8 a 1.0','1.5 a 1.8','2.5 a 3.0','Sempre 16px'],1,'WCAG recomenda no mínimo 1.5 para texto corrido. Valores entre 1.5 e 1.8 são ideais para a maioria dos textos. Abaixo de 1.2, o texto fica sufocante.'),
    'Você domina line-height! Esse ajuste sutil melhora drasticamente a legibilidade e é essencial para um design inclusivo.',
    'c16','Defina no p: font-size: 1.125rem e line-height: 1.75. No h1: line-height: 1.2 (títulos podem ser mais comprimidos).',
    'line-height sem unidade (ex: 1.6) é multiplicado pelo font-size. É a forma recomendada.',
    'Para parágrafos, use 1.5 a 1.8. Para títulos grandes, 1.1 a 1.3 é mais elegante.',
    'Código:\nh1 { line-height: 1.2; }\np { font-size: 1.125rem; line-height: 1.75; }'
  ),

  mkLesson('Espaçamento de Letras','css',7,'Propriedade letter-spacing',
    `h1 {\n  /* adicione letter-spacing */\n}\n.subtitulo {\n  text-transform: uppercase;\n}`,
    `function v(o,c){return c.includes('letter-spacing:');}v;`,
    'Letras muito juntas são difíceis de ler. Letras muito espaçadas parecem esparsas. O letter-spacing é o ajuste fino entre caracteres — muito usado em títulos e rótulos em maiúsculo.',
    'letter-spacing em px ou em',
    'letter-spacing aceita valores positivos (mais espaço) ou negativos (menos espaço), em px ou em. Em títulos grandes, um valor de 1-3px abre o texto elegantemente. Em textos em caps, 2-4px é padrão.',
    `h1 {\n  letter-spacing: 2px;   /* título aberto */\n}\n.tag {\n  text-transform: uppercase;\n  letter-spacing: 3px;   /* rótulo espaçado */\n  font-size: 0.75rem;\n}`,
    'word-spacing — espaço entre palavras',
    'Similar ao letter-spacing, word-spacing controla o espaço entre palavras (não letras). É útil para texto justificado ou efeitos tipográficos especiais.',
    `.slogan {\n  letter-spacing: 0.1em;  /* proporcional à fonte */\n  word-spacing: 0.2em;\n}`,
    'Adicione letter-spacing: 2px no h1 do editor. No .subtitulo (já em uppercase), use letter-spacing: 4px.',
    chk('Por que letter-spacing é especialmente útil em textos em maiúsculo?',['Para fazer parecer menor','Texto em maiúsculo fica denso — letter-spacing melhora a leiturabilidade','Por uma regra CSS obrigatória','Não tem relação com maiúsculo'],1,'Texto todo em maiúsculo perde o ritmo visual das ascendentes e descendentes, ficando denso. letter-spacing adiciona respiro e melhora muito a leitura.'),
    'Você controla o espaçamento de letras! Essa propriedade sutil é o que diferencia um design amador de um profissional em detalhes tipográficos.',
    'c17','No h1, use letter-spacing: 3px. No .label com text-transform: uppercase, use letter-spacing: 5px e font-size: 0.75rem.',
    'letter-spacing usa px ou em. Valores positivos aumentam o espaço, negativos diminuem.',
    'Para textos em uppercase, letter-spacing de 3-6px é uma prática padrão de design.',
    'Código:\nh1 { letter-spacing: 3px; }\n.label { text-transform: uppercase; letter-spacing: 5px; font-size: 0.75rem; }'
  ),
];

// ─── MÓDULO 4 — Espaçamento ────────────────────────────────────────────────────
const mod4: LessonInput[] = [

  mkLesson('Margem Externa','css',1,'Propriedade margin',
    `.box {\n  background-color: lightblue;\n  /* adicione margin */\n}`,
    `function v(o,c){return c.includes('margin')&&c.includes(':');}v;`,
    'Elementos grudados uns nos outros são visualmente sufocantes. Margin é o espaço EXTERNO ao redor de um elemento — como a distância respeitosa entre pessoas numa fila.',
    'margin: shorthand e valores individuais',
    'margin pode receber 1, 2, 3 ou 4 valores. Com 4 valores: top, right, bottom, left (sentido horário). Com 2 valores: top/bottom e left/right. "margin: auto" centraliza elementos de bloco horizontalmente.',
    `.box {\n  margin: 20px;           /* todos os lados */\n  margin: 10px 20px;      /* top/bottom left/right */\n  margin: 10px 20px 30px 20px; /* top right bottom left */\n}\n.centralizado {\n  margin: 0 auto; /* centraliza horizontalmente */\n}`,
    'Colapso de margens',
    'Margens verticais entre elementos de bloco se "colapsam" — dois elementos com margin-bottom: 20px e margin-top: 20px terão 20px entre eles (não 40px). Só margens verticais se colapsam.',
    `.paragrafo {\n  margin-top: 16px;\n  margin-bottom: 16px;\n  /* Se dois .paragrafo se seguem,\n     o espaço entre eles é 16px (não 32px) */\n}`,
    'Adicione margin: 20px no .box. Depois experimente margin: 40px 20px e observe como os espaços mudam.',
    chk('O que margin: 0 auto faz num elemento de bloco?',['Remove todo o espaço','Centraliza o elemento horizontalmente','Adiciona espaço vertical de 0 e auto horizontal','Não faz nada'],1,'margin: 0 auto define 0 para topo e base, e "auto" para esquerda e direita. "Auto" distribui o espaço igualmente, centralizando o elemento. O elemento deve ter width definido para funcionar.'),
    'Você domina margins! Esse é um dos espaçamentos mais usados em qualquer layout — entre cards, entre seções, para centralizar contêineres.',
    'c18','Centralize .container com margin: 0 auto e dê ao .card margin-bottom: 24px.',
    'margin: 0 auto centraliza elementos de bloco — mas o elemento precisa ter width definido.',
    'margin-bottom: 24px adiciona espaço abaixo do elemento (separando do próximo).',
    'Código:\n.container { width: 800px; margin: 0 auto; }\n.card { margin-bottom: 24px; }'
  ),

  mkLesson('Preenchimento Interno','css',2,'Propriedade padding',
    `.btn {\n  background-color: purple;\n  color: white;\n  /* adicione padding */\n}`,
    `function v(o,c){return c.includes('padding')&&c.includes(':');}v;`,
    'Margin afasta elementos de outros. Padding é diferente: é o espaço INTERNO entre o conteúdo e a borda do próprio elemento — como o estofamento de um sofá.',
    'padding: mesma sintaxe do margin',
    'padding usa a mesma lógica de shorthand que margin: 1, 2, 3 ou 4 valores em sentido horário. A diferença é que padding é interno — ele aumenta o tamanho visual do elemento e exibe a cor de fundo.',
    `.btn {\n  padding: 12px 24px; /* top/bottom left/right */\n  /* botão respira dentro da própria caixa */\n}\n.card {\n  padding: 24px; /* espaço interno uniforme */\n}`,
    'margin vs padding: a diferença visual',
    'margin cria espaço fora do elemento (entre ele e os vizinhos). padding cria espaço dentro (entre conteúdo e borda). A cor de fundo preenche até o padding — mas não o margin.',
    `/* Visualizando a diferença: */\n.box {\n  background-color: lightblue; /* preenche até o padding */\n  padding: 20px;    /* espaço interno AZUL */\n  margin: 10px;     /* espaço externo TRANSPARENTE */\n}`,
    'Adicione padding: 12px 24px no .btn do editor. Observe como o botão "respira" sem aumentar o espaço externo.',
    chk('O que aumenta ao adicionar padding em um elemento?',['O espaço entre o elemento e seus vizinhos','O espaço interno entre o conteúdo e a borda do elemento','O tamanho da fonte','A transparência'],1,'padding aumenta o espaço interno do elemento — entre o conteúdo e a borda. A cor de fundo se estende pelo padding. O tamanho total do elemento aumenta junto com o padding.'),
    'Você entende padding! Botões, cards e qualquer container usam padding para criar espaço interno confortável.',
    'c19','No .btn, adicione padding: 14px 28px. No .card, adicione padding: 24px.',
    'padding é interno — aumenta o espaço dentro do elemento. margin é externo.',
    'padding: 14px 28px significa 14px em cima/baixo e 28px na esquerda/direita.',
    'Código:\n.btn { padding: 14px 28px; }\n.card { padding: 24px; }'
  ),

  mkLesson('Borda','css',3,'Propriedade border',
    `.card {\n  padding: 20px;\n  /* adicione border */\n}`,
    `function v(o,c){return c.includes('border:')||c.includes('border-');}v;`,
    'Bordas definem limites visuais. Podem ser sutis (1px cinza) ou dramaticas (4px roxo). São o contorno que dá definição a cards, botões e inputs.',
    'border: shorthand de três valores',
    'border é um shorthand para espessura, estilo e cor. O estilo é obrigatório — sem ele, a borda não aparece. Estilos comuns: solid (sólida), dashed (tracejada), dotted (pontilhada).',
    `.card {\n  border: 1px solid #e2e8f0;   /* borda sutil */\n}\n.destaque {\n  border: 3px solid #7c3aed;   /* borda de destaque */\n}\n.separador {\n  border-bottom: 2px dashed #94a3b8; /* só embaixo */\n}`,
    'Bordas individuais',
    'Você pode estilizar cada lado separadamente: border-top, border-right, border-bottom, border-left. Também pode misturar — uma borda sólida embaixo e sem borda nos outros lados.',
    `.input {\n  border: none;\n  border-bottom: 2px solid #7c3aed; /* estilo material design */\n  outline: none;\n}`,
    'Adicione border: 2px solid #7c3aed no .card do editor. Depois experimente border-top com cor diferente.',
    chk('Qual é o shorthand correto para criar uma borda sólida de 1px?',['border: solid 1px','border: 1px solid cor','border-style: 1px solid','border(1px, solid, cor)'],1,'border: espessura estilo cor — essa é a ordem. Os três valores são separados por espaço, sem vírgulas. border: 1px solid #ccc é o uso mais comum.'),
    'Você cria bordas em CSS! Junto com padding e border-radius, bordas são a base visual de qualquer card ou botão profissional.',
    'c20','Dê ao .card border: 1px solid #e2e8f0. Ao .btn adicione border: 2px solid #7c3aed. Ao input adicione border-bottom: 2px solid #7c3aed e border-top: none, border-left: none, border-right: none.',
    'border é shorthand: espessura estilo cor. O estilo (solid, dashed, dotted) é obrigatório.',
    'Para bordas individuais, use border-top, border-right, border-bottom, border-left.',
    'Código:\n.card { border: 1px solid #e2e8f0; }\n.btn { border: 2px solid #7c3aed; }'
  ),

  mkLesson('Borda Arredondada','css',4,'Propriedade border-radius',
    `.btn {\n  padding: 12px 24px;\n  background-color: #7c3aed;\n  color: white;\n  border: none;\n  /* adicione border-radius */\n}`,
    `function v(o,c){return c.includes('border-radius:');}v;`,
    'Cantos arredondados transformam elementos rígidos em algo amigável e moderno. Botões, avatares, cards — o arredondamento define o estilo visual de toda uma interface.',
    'border-radius: do sutil ao circular',
    'border-radius arredonda os cantos de qualquer elemento. Valores pequenos (4-8px) são sutis. Valores grandes (24px) são pronunciados. border-radius: 50% transforma quadrados em círculos perfeitos.',
    `.btn {\n  border-radius: 8px;  /* sutil */\n}\n.pill {\n  border-radius: 9999px; /* pílula */\n}\n.avatar {\n  width: 60px;\n  height: 60px;\n  border-radius: 50%; /* círculo perfeito */\n}`,
    'Cantos individuais',
    'Assim como border, você pode arredondar cantos individualmente: border-top-left-radius, border-top-right-radius, border-bottom-right-radius, border-bottom-left-radius.',
    `.card {\n  border-radius: 12px 12px 0 0; /* só cantos de cima */\n}\n.chip {\n  border-radius: 0 8px 8px 0; /* só cantos da direita */\n}`,
    'Adicione border-radius: 8px no .btn. Depois experimente 9999px para o estilo "pílula". Crie um avatar quadrado e use border-radius: 50%.',
    chk('O que border-radius: 50% faz num elemento com width e height iguais?',['Cria um semicírculo','Deixa o elemento transparente','Transforma o elemento num círculo perfeito','Remove a borda'],2,'border-radius: 50% define os cantos em 50% da metade do elemento. Em elementos quadrados (width = height), isso cria um círculo perfeito. É a técnica padrão para avatares circulares.'),
    'Você arredonda cantos com CSS! border-radius é um dos estilos que mais impacta visualmente — e uma das propriedades mais usadas em qualquer design moderno.',
    'c21','Crie .btn com border-radius: 9999px (pílula), .card com border-radius: 12px e .avatar 60x60px com border-radius: 50%.',
    'border-radius: 50% transforma quadrados em círculos. Use apenas em elementos com width = height.',
    'Para o estilo "pílula", use um valor grande como 9999px — isso garante que funcione em qualquer tamanho.',
    'Código:\n.btn { border-radius: 9999px; }\n.card { border-radius: 12px; }\n.avatar { width: 60px; height: 60px; border-radius: 50%; }'
  ),

  mkLesson('Box Sizing','css',5,'Propriedade box-sizing',
    `* {\n  /* reset universal de box-sizing */\n}\n.box {\n  width: 200px;\n  padding: 20px;\n  border: 4px solid purple;\n}`,
    `function v(o,c){return c.includes('box-sizing:')&&c.includes('border-box');}v;`,
    'Você define width: 200px, adiciona padding e border — e o elemento fica com 248px de largura. Parece bug, mas é o comportamento padrão do CSS. box-sizing resolve isso de vez.',
    'O modelo de caixa padrão (content-box)',
    'Por padrão, width e height definem apenas o conteúdo. padding e border são ADICIONADOS por fora. Então width: 200px + padding: 20px + border: 4px = 248px de largura total.',
    `/* content-box (padrão) — problemático: */\n.box {\n  width: 200px;\n  padding: 20px;   /* + 40px */\n  border: 4px solid; /* + 8px */\n  /* tamanho real: 248px! */\n}`,
    'border-box — o que todo dev usa',
    'Com box-sizing: border-box, o width e height INCLUEM padding e border. 200px é 200px sempre. A regra universal * { box-sizing: border-box; } é o primeiro CSS de todo projeto profissional.',
    `/* Reset universal — sempre faça isso: */\n* {\n  box-sizing: border-box;\n}\n\n.box {\n  width: 200px; /* agora sempre 200px */\n  padding: 20px;\n  border: 4px solid;\n}`,
    'Aplique box-sizing: border-box no seletor * do editor. Observe como o .box agora respeita o width de 200px independente do padding.',
    chk('O que box-sizing: border-box faz?',['Remove padding e border','Faz o width incluir padding e border no tamanho total','Dobra o tamanho do elemento','Define a borda como invisível'],1,'border-box inclui padding e border dentro do width/height definido. Se você diz width: 200px, o elemento terá EXATAMENTE 200px — o padding e a border ficam para dentro.'),
    'Você aprendeu o reset de box-sizing! Essa é a primeira regra CSS de todo projeto profissional. Nunca esqueça o * { box-sizing: border-box; }.',
    'c22','Adicione * { box-sizing: border-box; } e observe que .box (com width: 200px, padding: 20px, border: 4px solid) permanece com 200px.',
    '* seleciona TODOS os elementos da página. É o seletor universal.',
    'box-sizing: border-box é o valor que "corrige" o modelo de caixa para ser intuitivo.',
    'Código:\n* { box-sizing: border-box; }\n.box { width: 200px; padding: 20px; border: 4px solid purple; }'
  ),
];

// ─── MÓDULO 5 — Seletores ──────────────────────────────────────────────────────
const mod5: LessonInput[] = [

  mkLesson('Seletores de Classe','css',1,'Seletor .classe',
    `/* Estilize elementos por classe */\n`,
    `function v(o,c){return c.includes('.')&&c.includes('{')&&c.includes(':');}v;`,
    'Um elemento pode usar class="" para pertencer a um "grupo". Seletores de classe estilizam todos os membros desse grupo de uma vez — como dar um uniforme para um time.',
    'Como usar seletores de classe',
    'No CSS, um seletor de classe começa com ponto (.). .card seleciona todos os elementos com class="card". Um elemento pode ter múltiplas classes e cada classe pode ter múltiplos elementos.',
    `/* CSS: */\n.card {\n  background-color: white;\n  padding: 24px;\n  border-radius: 12px;\n}\n.destaque {\n  border-left: 4px solid #7c3aed;\n}`,
    'Múltiplas classes no mesmo elemento',
    'No HTML, você pode combinar classes: class="card destaque" aplica os estilos de ambas. No CSS, .card.destaque (sem espaço) seleciona elementos que têm AS DUAS classes simultaneamente.',
    `/* Seletor combinado: */\n.card.destaque {\n  box-shadow: 0 4px 20px rgba(124,58,237,0.3);\n}\n/* Só aplica a elementos com class="card destaque" */`,
    'Escreva regras para .card (fundo branco, padding 24px, border-radius 12px) e .tag (fundo roxo, cor branca, padding 4px 8px, border-radius 9999px).',
    chk('Como selecionar elementos com class="titulo"?',['#titulo { }','*titulo { }','.titulo { }','<titulo> { }'],2,'Seletores de classe começam com ponto. .titulo seleciona todos os elementos com class="titulo". # é para IDs, * é universal, e <> não é CSS.'),
    'Você domina classes CSS! Classes são a forma mais usada de seleção em projetos reais — permitem reutilizar estilos em qualquer elemento da página.',
    'c23','Crie .btn-primario com background-color: #7c3aed, color: white, padding: 12px 24px, border-radius: 8px. Crie .btn-secundario com border: 2px solid #7c3aed, color: #7c3aed, padding: 12px 24px.',
    'Seletores de classe começam com ponto (.). .btn-primario seleciona class="btn-primario".',
    'Classes permitem reutilização — qualquer elemento com aquela class herda os estilos.',
    'Código:\n.btn-primario { background-color: #7c3aed; color: white; padding: 12px 24px; border-radius: 8px; }\n.btn-secundario { border: 2px solid #7c3aed; color: #7c3aed; padding: 12px 24px; }'
  ),

  mkLesson('Seletores de ID','css',2,'Seletor #id',
    `/* Estilize elementos únicos por ID */\n`,
    `function v(o,c){return c.includes('#')&&c.includes('{')&&c.includes(':');}v;`,
    'Enquanto classes são para grupos, IDs são para elementos únicos e exclusivos. O cabeçalho principal, o logo, o modal de confirmação — cada um é único na página.',
    'Como usar seletores de ID',
    'No CSS, seletores de ID começam com #. #navbar seleciona o elemento com id="navbar". IDs devem ser únicos por página — usar o mesmo ID em dois elementos é inválido em HTML.',
    `/* CSS: */\n#navbar {\n  background-color: #0f172a;\n  position: fixed;\n  top: 0;\n  width: 100%;\n}\n#logo {\n  font-size: 1.5rem;\n  font-weight: 700;\n}`,
    'ID vs Classe: quando usar cada um',
    'Use classe (.nome) quando o estilo pode se repetir em múltiplos elementos. Use ID (#nome) para estilos únicos de um elemento específico. Em CSS moderno, classes são preferidas — IDs têm especificidade muito alta e podem causar conflitos.',
    `/* Preferência moderna: use classes */\n.navbar { } /* OK para reutilizar */\n\n/* ID para JavaScript: */\ndocument.getElementById("modal") /* IDs são úteis em JS */`,
    'Estilize #header com background-color e padding, e #logo com font-size e font-weight. Observe como são selecionados pelo # no CSS.',
    chk('Quantos elementos podem ter o mesmo ID numa página?',['Ilimitados','Um por tipo de tag','Apenas um','Dois no máximo'],2,'ID deve ser único na página — apenas um elemento pode ter um id="nome" específico. Duplicar IDs é HTML inválido. Para estilos reutilizáveis, use classes.'),
    'Você domina seletores de ID! Em CSS moderno, classes são mais comuns, mas IDs são essenciais para JavaScript e para elementos verdadeiramente únicos como navbar e footer.',
    'c24','Estilize #hero com min-height: 100vh, background: linear-gradient(135deg, #0f172a, #1e293b), color: white, text-align: center. E #logo com font-size: 1.5rem, font-weight: 800.',
    'Seletores de ID começam com # (hash/jogo-da-velha).',
    'ID é único — só um elemento por página pode ter aquele id="".',
    'Código:\n#hero { min-height: 100vh; background: linear-gradient(135deg, #0f172a, #1e293b); color: white; }\n#logo { font-size: 1.5rem; font-weight: 800; }'
  ),

  mkLesson('Múltiplos Seletores','css',3,'Agrupamento e combinação de seletores',
    `/* Experimente agrupar e combinar seletores */\n`,
    `function v(o,c){return (c.includes(',')&&c.includes('{'))||(c.match(/\s+[.#a-z]/i)&&c.includes('{'));}v;`,
    'Repetir as mesmas regras CSS para h1, h2 e h3 separadamente é desperdício. CSS permite agrupar e combinar seletores de formas poderosas.',
    'Agrupamento com vírgula',
    'Separe seletores com vírgula para aplicar as mesmas regras a múltiplos elementos. h1, h2, h3 { } aplica o CSS para os três tipos de título de uma vez.',
    `/* Agrupamento: */\nh1, h2, h3 {\n  font-family: 'Georgia', serif;\n  color: #0f172a;\n}\n\n.btn-primary, .btn-secondary {\n  padding: 12px 24px;\n  border-radius: 8px;\n}`,
    'Seletores descendentes (espaço)',
    'Um espaço entre seletores significa "dentro de". .card p seleciona todos os <p> que estão dentro de um elemento com class="card". Isso permite estilos contextuais precisos.',
    `/* Seletor descendente: */\n.card p {\n  color: #64748b; /* só p dentro de .card */\n}\n\n/* Filho direto (>): */\n.menu > li {\n  list-style: none; /* só li diretos do .menu */\n}`,
    'Agrupe h1, h2, h3 com cor e font-family compartilhadas. Use .card p para estilizar parágrafos dentro de cards de forma diferente.',
    chk('O que .card p { } seleciona?',['O elemento .card e todos os p da página','Apenas o elemento com class="card p"','Todos os <p> que estão dentro de elementos com class="card"','Apenas o primeiro <p> de .card'],2,'.card p (com espaço) é um seletor descendente: seleciona todos os <p> que são descendentes de um elemento com class="card", em qualquer nível de aninhamento.'),
    'Você combina seletores como um profissional! Agrupamento e seletores descendentes reduzem repetição e criam regras contextuais poderosas.',
    'c25','Agrupe h1, h2, h3 com font-family e color compartilhados. Use .navbar a para estilizar links dentro da navbar sem afetar outros links.',
    'Separe seletores com vírgula para compartilhar estilos. Use espaço para relação pai-filho.',
    'h1, h2 { } = mesmas regras. .nav a { } = links dentro de .nav.',
    'Código:\nh1, h2, h3 { color: #0f172a; font-family: serif; }\n.navbar a { color: white; text-decoration: none; }'
  ),

  mkLesson('Pseudo-classes','css',4,'Pseudo-classes CSS',
    `li {\n  padding: 8px;\n  /* experimente pseudo-classes */\n}`,
    `function v(o,c){return c.includes(':')&&(c.includes('first-child')||c.includes('last-child')||c.includes('nth-child')||c.includes('not('));}v;`,
    'E se você quiser estilizar apenas o primeiro item de uma lista, ou alterar cor em elementos pares? Pseudo-classes selecionam estados ou posições específicas dos elementos.',
    'Pseudo-classes estruturais',
    'Pseudo-classes começam com : e se anexam a seletores. :first-child seleciona o primeiro filho. :last-child o último. :nth-child(n) permite padrões como "a cada 2" com :nth-child(even).',
    `li:first-child {\n  border-top: none; /* remove borda do primeiro */\n}\nli:last-child {\n  margin-bottom: 0; /* remove margem do último */\n}\ntr:nth-child(even) {\n  background-color: #f8fafc; /* linhas pares de tabela */\n}`,
    ':not() — o inverso',
    ':not() seleciona elementos que NÃO correspondem ao seletor dentro dos parênteses. li:not(:last-child) seleciona todos os li EXCETO o último. Muito útil para remover bordas/margens do último elemento.',
    `li:not(:last-child) {\n  border-bottom: 1px solid #e2e8f0;\n  /* adiciona divisor em todos exceto o último */\n}`,
    'Use li:first-child para destacar o primeiro item. Use li:nth-child(even) para fundo alternado. Use li:last-child para remover a margem inferior.',
    chk('O que li:nth-child(odd) seleciona?',['Todos os li','O li ímpar (1º, 3º, 5º...)','O li par (2º, 4º, 6º...)','Apenas o 3º li'],1,':nth-child(odd) = ímpar = 1º, 3º, 5º... :nth-child(even) = par = 2º, 4º, 6º... Você também pode usar números: :nth-child(3) seleciona exatamente o 3º.'),
    'Você usa pseudo-classes! Elas permitem estilizar elementos por posição sem adicionar classes no HTML — o CSS fica mais limpo e inteligente.',
    'c26','Use li:first-child com font-weight: bold, li:nth-child(even) com background-color: #f8fafc, e li:not(:last-child) com border-bottom: 1px solid #e2e8f0.',
    'Pseudo-classes se anexam ao seletor com : (dois-pontos simples).',
    ':nth-child(even) = pares, :nth-child(odd) = ímpares, :not(seletor) = exceto aqueles.',
    'Código:\nli:first-child { font-weight: bold; }\nli:nth-child(even) { background-color: #f8fafc; }\nli:not(:last-child) { border-bottom: 1px solid #e2e8f0; }'
  ),

  mkLesson('Efeito Hover','css',5,'Pseudo-classe :hover',
    `.btn {\n  background-color: #7c3aed;\n  color: white;\n  padding: 12px 24px;\n  border-radius: 8px;\n  border: none;\n  cursor: pointer;\n  /* adicione :hover abaixo */\n}`,
    `function v(o,c){return c.includes(':hover')&&c.includes('{');}v;`,
    'Quando você passa o mouse sobre um botão e ele muda de cor, isso é :hover. É a micro-interação mais fundamental da web — dá feedback visual e faz a interface parecer viva.',
    'Como funciona :hover',
    ':hover é uma pseudo-classe que aplica estilos quando o mouse está sobre o elemento. Combine com transition para animar a mudança suavemente. Qualquer elemento pode ter :hover — não só botões.',
    `.btn:hover {\n  background-color: #6d28d9; /* mais escuro */\n  transform: translateY(-2px); /* levanta um pouco */\n}\n\n.card:hover {\n  box-shadow: 0 8px 30px rgba(0,0,0,0.15);\n}`,
    'transition para suavizar o hover',
    'Sem transition, a mudança é instantânea (brusca). Com transition: all 0.2s ease, a mudança acontece suavemente em 0.2 segundos. A transition fica na regra BASE, não no :hover.',
    `.btn {\n  transition: all 0.2s ease; /* fica na regra BASE */\n}\n.btn:hover {\n  background-color: #6d28d9;\n}`,
    'Adicione .btn:hover com uma cor mais escura. Depois adicione transition: all 0.2s ease na regra .btn base. Observe a diferença suave.',
    chk('Onde a propriedade transition deve ser colocada?',['Dentro do :hover','Fora do :hover, na regra base do elemento','Em ambos','No <style> antes de qualquer regra'],1,'transition fica na regra BASE do elemento (não no :hover). Isso garante que a animação aconteça tanto ao entrar no hover quanto ao sair. Se ficar só no :hover, a saída é instantânea.'),
    'Você domina :hover! Com transition adicionado, seus elementos têm micro-animações profissionais. Isso eleva a qualidade percebida de qualquer interface.',
    'c27','No .btn, adicione transition: all 0.2s ease. No .btn:hover, mude background-color para #5b21b6 e adicione transform: translateY(-2px).',
    'transition fica na regra base. :hover é um seletor separado com as mudanças que ocorrem ao passar o mouse.',
    'transform: translateY(-2px) move o botão 2px para cima — efeito de "saltar" muito usado em design.',
    'Código:\n.btn { transition: all 0.2s ease; }\n.btn:hover { background-color: #5b21b6; transform: translateY(-2px); }'
  ),
];

// ─── MÓDULO 6 — Layout ─────────────────────────────────────────────────────────
const mod6: LessonInput[] = [

  mkLesson('Propriedade Display','css',1,'Propriedade display',
    `.exemplo {\n  /* experimente display */\n}`,
    `function v(o,c){return c.includes('display:');}v;`,
    'Cada elemento HTML tem um comportamento padrão de layout. display é a propriedade que controla esse comportamento — é a base de qualquer layout CSS.',
    'O que é display?',
    'display define como um elemento se comporta no fluxo da página. O valor padrão de tags como div é "block". De tags como span é "inline". Você pode mudar esse comportamento a qualquer momento.',
    `/* Valores mais comuns: */\ndiv  { display: block; }        /* linha inteira */\nspan { display: inline; }       /* fluxo do texto */\nimg  { display: inline-block; } /* inline com dimensões */\nnav  { display: flex; }         /* layout flexível */\n.grid{ display: grid; }         /* layout em grade */`,
    'display: none — ocultar elementos',
    'display: none remove o elemento da página completamente (ele não ocupa espaço). É diferente de visibility: hidden, que oculta mas mantém o espaço. display: none é muito usado para mostrar/ocultar menus e modais.',
    `.menu-mobile {\n  display: none; /* oculto por padrão */\n}\n.menu-mobile.aberto {\n  display: flex; /* visível quando tem classe "aberto" */\n}`,
    'Adicione display: flex ao .container, display: block ao .titulo e display: none ao .oculto. Observe como cada um afeta o layout.',
    chk('O que display: none faz?',['Torna o elemento transparente','Remove o elemento da renderização e do fluxo','Diminui o elemento para 0px','Oculta apenas o texto'],1,'display: none remove o elemento completamente do layout — como se não existisse no HTML. Não ocupa espaço. visibility: hidden é diferente: oculta mas mantém o espaço.'),
    'Você entende display! É a propriedade de layout mais fundamental do CSS. block, inline, flex, grid e none são os valores que você vai usar em todo projeto.',
    'c28','Use display: none em .modal-fechado e display: flex em .navbar. Adicione display: grid em .galeria.',
    'display controla o comportamento de layout do elemento. Cada valor tem comportamentos muito diferentes.',
    'display: none oculta e remove do fluxo. display: flex ativa o Flexbox. display: grid ativa o Grid.',
    'Código:\n.modal-fechado { display: none; }\n.navbar { display: flex; }\n.galeria { display: grid; }'
  ),

  mkLesson('Display Block','css',2,'Valor display: block',
    `span {\n  background-color: lightblue;\n  padding: 8px;\n  /* adicione display: block */\n}`,
    `function v(o,c){return c.includes('display:')&&c.includes('block');}v;`,
    'Elementos block são como tijolos numa parede: cada um ocupa uma linha inteira, empilhados verticalmente. Div, p, h1 são block por natureza — mas qualquer elemento pode virar block.',
    'Características do display: block',
    'Um elemento block: (1) ocupa toda a largura disponível, (2) começa numa nova linha, (3) respeita width, height, margin e padding completos. É o modo padrão de divs, parágrafos e headings.',
    `/* Tornando span em bloco: */\nspan {\n  display: block;\n  width: 200px;         /* agora aceita width */\n  margin-bottom: 16px;  /* margem vertical funciona */\n}\n\n/* Elemento block padrão: */\np {\n  /* já é block — ocupa linha inteira */\n  max-width: 65ch;      /* limita a largura para leiturabilidade */\n}`,
    'max-width e width em elementos block',
    'Elementos block aceitam width e max-width. max-width: 65ch é um truque de tipografia: 65 caracteres (ch) é a largura de leitura ideal para parágrafos. Combine com margin: 0 auto para centralizar.',
    `p {\n  max-width: 65ch;\n  margin: 0 auto;\n  line-height: 1.6;\n}`,
    'Adicione display: block ao span do editor. Observe como ele passa a ocupar a linha inteira e aceita width e height.',
    chk('Qual das tags abaixo é display: block por padrão?',['<span>','<a>','<img>','<div>'],3,'<div>, <p>, <h1>-<h6>, <ul>, <li>, <section>, <article> são block por padrão. <span>, <a>, <em>, <strong> são inline. <img> é inline-block.'),
    'Você entende display: block! Qualquer elemento pode se tornar block com display: block, ganhando controle total de dimensões e espaçamento.',
    'c29','Faça os links da .navbar virarem blocos com display: block, padding: 12px 16px e width: 100%.',
    'display: block faz o elemento ocupar a linha inteira e aceitar width, height e margin vertical.',
    'Depois de display: block, o elemento se comporta como um div: empilha verticalmente e aceita todas as propriedades de dimensão.',
    'Código:\n.navbar a { display: block; padding: 12px 16px; width: 100%; }'
  ),

  mkLesson('Display Inline','css',3,'Valor display: inline',
    `strong {\n  /* strong já é inline */\n  background-color: #fef08a;\n}\n\ndiv {\n  /* torne um div inline */\n}`,
    `function v(o,c){return c.includes('display:')&&c.includes('inline')&&!c.includes('inline-block')&&!c.includes('inline-flex');}v;`,
    'Links, spans, negritos — eles fluem junto com o texto sem quebrar a linha. Elementos inline são os cidadãos do fluxo tipográfico.',
    'Características do display: inline',
    'Um elemento inline: (1) fica no fluxo do texto, (2) NÃO quebra linha, (3) só aceita margin e padding horizontais (left e right). Width e height são ignorados. É o padrão de span, a, strong, em.',
    `/* inline NÃO aceita width/height: */\nspan {\n  display: inline;\n  width: 100px;  /* ignorado! */\n  padding: 4px 8px; /* só horizontal funciona completamente */\n}`,
    'Quando usar display: inline',
    'Use inline quando quiser que um elemento flua com o texto sem quebrá-lo. Exemplo: adicionar fundo em uma palavra dentro de um parágrafo, ou criar tags/badges dentro de texto corrido.',
    `p {\n  font-size: 1rem;\n}\n.tag {\n  display: inline;\n  background-color: #ddd1fe;\n  padding: 2px 6px;\n  border-radius: 4px;\n  font-size: 0.75rem;\n}`,
    'Adicione display: inline ao div do editor. Observe como ele para de quebrar linha e passa a fluir com o texto.',
    chk('Por que width: 200px não funciona em elementos display: inline?',['É um bug do CSS','Elementos inline não respeitam dimensões explícitas — seu tamanho é definido pelo conteúdo','width não funciona sem height','É necessário usar !important'],1,'Elementos inline têm tamanho definido pelo conteúdo. Ignoram width e height explícitos. Para ter controle de dimensões E ficar no fluxo, use inline-block.'),
    'Você entende display: inline! Agora sabe por que spans e links não quebram linha — e quando tornar um elemento inline intencionalmente.',
    'c30','Faça .badge ser inline com background-color: #ddd1fe, padding: 2px 8px e border-radius: 9999px. Observe como ele fica dentro do fluxo do texto.',
    'display: inline faz o elemento fluir com o texto. Não quebra linha.',
    'inline ignora width e height — só aceita padding e margin horizontais completamente.',
    'Código:\n.badge { display: inline; background-color: #ddd1fe; padding: 2px 8px; border-radius: 9999px; }'
  ),

  mkLesson('Display Inline-Block','css',4,'Valor display: inline-block',
    `.btn {\n  background-color: #7c3aed;\n  color: white;\n  /* experimente inline-block */\n}`,
    `function v(o,c){return c.includes('display:')&&c.includes('inline-block');}v;`,
    'O melhor dos dois mundos: fica no fluxo do texto como inline, mas aceita dimensões como block. inline-block é a base de botões, badges e ícones.',
    'inline-block: o híbrido perfeito',
    'display: inline-block combina: fica ao lado de outros elementos (como inline) e aceita width, height, padding e margin completos (como block). É o valor padrão de <img> e <button>.',
    `.btn {\n  display: inline-block;\n  width: 160px;\n  padding: 12px 24px;   /* padding completo */\n  margin: 8px;          /* margin completo */\n  text-align: center;\n}`,
    'Comparação dos três valores',
    'block: nova linha, largura total, dimensões completas. inline: no fluxo, sem dimensões. inline-block: no fluxo, com dimensões. Para botões que ficam lado a lado, inline-block é a resposta clássica.',
    `/* Botões lado a lado: */\n.btn {\n  display: inline-block;\n  padding: 10px 20px;\n}\n/* Os botões ficam na mesma linha automaticamente */`,
    'Adicione display: inline-block no .btn do editor. Depois adicione width e padding e veja como respeita as dimensões sem quebrar linha.',
    chk('Qual a vantagem de inline-block sobre inline?',['É mais rápido','Aceita width, height e padding/margin completos mantendo o fluxo inline','Suporta animações','Não tem diferença'],1,'inline-block é inline que aceita dimensões. Isso é crucial para botões, cards e badges: você quer que fiquem lado a lado (inline) mas com tamanho controlado (block).'),
    'Você domina inline-block! Botões lado a lado, ícones no fluxo do texto, badges dimensionados — tudo isso usa inline-block. É uma das ferramentas mais versáteis do CSS.',
    'c31','Use display: inline-block nos .btn com padding: 12px 24px, margin: 4px e border-radius: 8px. Observe como ficam lado a lado.',
    'inline-block = comportamento inline (lado a lado) + aceita dimensões como block.',
    'Adicione width explícito para ver como o elemento mantém o tamanho e ainda fica no fluxo.',
    'Código:\n.btn { display: inline-block; padding: 12px 24px; margin: 4px; border-radius: 8px; }'
  ),

  mkLesson('Introdução ao Flexbox','css',5,'display: flex',
    `.container {\n  /* ative o flexbox */\n  background-color: #f1f5f9;\n  padding: 20px;\n}`,
    `function v(o,c){return c.includes('display:')&&c.includes('flex')&&!c.includes('inline-flex');}v;`,
    'Alinhar elementos lado a lado, centralizá-los vertical e horizontalmente, distribuir espaço igualmente — isso era difícil antes do Flexbox. Hoje, uma linha de CSS resolve.',
    'display: flex e o eixo principal',
    'Quando você coloca display: flex num contêiner, os filhos diretos se tornam "flex items" e se organizam numa linha horizontal por padrão. O eixo principal é horizontal, o cruzado é vertical.',
    `.container {\n  display: flex;\n  /* filhos ficam lado a lado automaticamente */\n}\n\n/* Os itens dentro de .container viram flex items */`,
    'Propriedades nos filhos: flex',
    'Nos filhos, você pode usar a propriedade flex para controlar o crescimento. flex: 1 faz todos os filhos crescerem igualmente para preencher o espaço. flex: 2 faz um filho ocupar o dobro do espaço.',
    `.container {\n  display: flex;\n}\n.item {\n  flex: 1; /* divide o espaço igualmente */\n}\n.item-grande {\n  flex: 2; /* ocupa o dobro */\n}`,
    'Ative display: flex no .container do editor. Observe os itens filho se organizando lado a lado automaticamente.',
    chk('O que display: flex faz com os filhos diretos do elemento?',['Os filhos somem','Os filhos se empilham verticalmente','Os filhos se tornam flex items e se organizam horizontalmente','Os filhos ficam todos com a mesma largura'],2,'display: flex ativa o Flexbox no contêiner. Os filhos diretos se tornam flex items e, por padrão, se organizam horizontalmente (em linha). A direção pode ser mudada com flex-direction.'),
    'Você ativou o Flexbox! Essa é a revolução do layout CSS moderno. Nas próximas aulas, você vai controlar alinhamento, direção e espaçamento com precisão.',
    'c32','Crie .navbar com display: flex. Os links filhos devem ficar lado a lado. Depois adicione .hero com display: flex e experimente a diferença.',
    'display: flex vai no CONTÊINER — não nos filhos. Os filhos herdam o comportamento flex automaticamente.',
    'Filhos de um flex container se organizam horizontalmente por padrão.',
    'Código:\n.navbar { display: flex; }\n.hero { display: flex; }'
  ),

  mkLesson('Justify Content','css',6,'Propriedade justify-content',
    `.container {\n  display: flex;\n  background-color: #f1f5f9;\n  padding: 16px;\n  /* adicione justify-content */\n}`,
    `function v(o,c){return c.includes('justify-content:');}v;`,
    'Você tem itens numa linha flex — mas eles estão todos grudados à esquerda. justify-content distribui esse espaço no eixo principal (horizontal por padrão).',
    'Valores de justify-content',
    'Os principais valores são: flex-start (esquerda — padrão), flex-end (direita), center (centro), space-between (espaço entre os itens), space-around (espaço ao redor), space-evenly (espaço igual).',
    `.navbar {\n  display: flex;\n  justify-content: space-between; /* logo à esq, menu à dir */\n}\n\n.hero-buttons {\n  display: flex;\n  justify-content: center; /* botões centralizados */\n}`,
    'O mais usado: space-between',
    'space-between é o valor mais usado em navbars: coloca o primeiro item no início e o último no fim, distribuindo os do meio com espaço igual. Perfeito para logo + menu.',
    `.navbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center; /* alinha verticalmente */\n  padding: 0 24px;\n}`,
    'Experimente todos os valores de justify-content no .container do editor: center, space-between, space-around, space-evenly.',
    chk('Qual valor de justify-content coloca o primeiro item no início e o último no fim?',['space-around','space-evenly','space-between','flex-end'],2,'space-between distribui os itens com o primeiro no início e o último no fim do contêiner. O espaço restante é dividido igualmente entre os itens. Ideal para navbars e layouts com dois lados.'),
    'Você distribui espaço com justify-content! space-between é provavelmente o valor que você vai usar 80% das vezes em navbars e headers.',
    'c33','Crie .navbar com display: flex, justify-content: space-between e align-items: center. Crie .botoes com display: flex e justify-content: center.',
    'justify-content controla o eixo HORIZONTAL (principal) no flex.',
    'space-between = primeiro à esquerda, último à direita, espaço igual entre os do meio.',
    'Código:\n.navbar { display: flex; justify-content: space-between; align-items: center; }\n.botoes { display: flex; justify-content: center; }'
  ),

  mkLesson('Align Items','css',7,'Propriedade align-items',
    `.container {\n  display: flex;\n  height: 200px;\n  background-color: #f1f5f9;\n  /* adicione align-items */\n}`,
    `function v(o,c){return c.includes('align-items:');}v;`,
    'justify-content controla o eixo horizontal. align-items controla o eixo vertical — permite centralizar itens no meio da tela com apenas duas linhas de CSS.',
    'Valores de align-items',
    'Os principais valores são: stretch (padrão — itens se esticam), flex-start (topo), flex-end (base), center (meio vertical). center é o Santo Graal do CSS — centraliza verticalmente.',
    `.hero {\n  display: flex;\n  justify-content: center; /* centro horizontal */\n  align-items: center;    /* centro vertical */\n  height: 100vh;\n  /* conteúdo perfeitamente centralizado! */\n}`,
    'align-self para um único item',
    'align-self permite que um item filho ignore o align-items do contêiner e se posicione diferente. Útil quando um item precisa ficar no topo enquanto os outros ficam centralizados.',
    `.container {\n  display: flex;\n  align-items: center;\n}\n.item-especial {\n  align-self: flex-start; /* sempre no topo */\n}`,
    'Adicione align-items: center ao .container (que já tem height: 200px). Observe os itens se centralizando verticalmente.',
    chk('O que align-items: center faz?',['Centraliza o texto dos itens','Centraliza os itens horizontalmente','Centraliza os itens verticalmente no eixo cruzado','Nenhuma das anteriores'],2,'align-items controla o eixo CRUZADO (perpendicular ao eixo principal). Com flex-direction padrão (row), o eixo cruzado é vertical. Então align-items: center centraliza verticalmente.'),
    'Você centraliza elementos com Flexbox! justify-content: center + align-items: center = elemento perfeitamente centralizado. Isso resolve um problema que os devs tinham há anos!',
    'c34','Crie .hero com display: flex, justify-content: center, align-items: center e height: 100vh. Tudo dentro ficará perfeitamente centralizado.',
    'align-items controla o eixo VERTICAL (cruzado) no Flexbox padrão.',
    'A combinação mágica: display: flex + justify-content: center + align-items: center = centraliza tudo.',
    'Código:\n.hero { display: flex; justify-content: center; align-items: center; height: 100vh; }'
  ),

  mkLesson('Flex Direction','css',8,'Propriedade flex-direction',
    `.container {\n  display: flex;\n  background-color: #f1f5f9;\n  padding: 16px;\n  /* experimente flex-direction */\n}`,
    `function v(o,c){return c.includes('flex-direction:');}v;`,
    'Por padrão, o Flexbox organiza itens em linhas horizontais. Mas e se você quiser uma coluna vertical? flex-direction muda o eixo principal — é como girar o layout 90 graus.',
    'Valores de flex-direction',
    'row (padrão — horizontal), row-reverse (horizontal invertido), column (vertical — de cima para baixo), column-reverse (vertical invertido). Com column, justify-content passa a controlar o eixo vertical.',
    `.sidebar {\n  display: flex;\n  flex-direction: column; /* itens empilhados */\n  gap: 8px;\n}\n.navbar {\n  display: flex;\n  flex-direction: row; /* itens lado a lado (padrão) */\n}`,
    'Combinando flex-direction e align/justify',
    'ATENÇÃO: quando flex-direction: column, os eixos se invertem! justify-content agora controla o eixo vertical e align-items controla o horizontal. Isso confunde muitos devs no início.',
    `.coluna-central {\n  display: flex;\n  flex-direction: column;\n  justify-content: center; /* agora vertical! */\n  align-items: center;     /* agora horizontal! */\n  height: 100vh;\n}`,
    'Adicione flex-direction: column ao .container. Observe os itens se empilhando verticalmente. Depois experimente flex-direction: row-reverse.',
    chk('Com flex-direction: column, o que justify-content controla?',['O eixo horizontal','O alinhamento de texto','O eixo vertical (eixo principal virou vertical)','Nada muda'],2,'flex-direction muda o eixo principal. Com column, o eixo principal é vertical — então justify-content controla posicionamento vertical, e align-items controla o horizontal. Os eixos se invertem!'),
    'Você controla a direção do Flexbox! Essa propriedade é essencial para sidebars, menus verticais e layouts de colunas. Lembre: com column, os eixos se invertem.',
    'c35','Crie .sidebar com display: flex, flex-direction: column, gap: 16px e width: 240px. Crie .hero com flex-direction: column, align-items: center, justify-content: center.',
    'flex-direction: column empilha os itens verticalmente.',
    'Lembre: com column, justify-content = vertical, align-items = horizontal.',
    'Código:\n.sidebar { display: flex; flex-direction: column; gap: 16px; width: 240px; }\n.hero { display: flex; flex-direction: column; align-items: center; justify-content: center; }'
  ),

  mkLesson('Gap no Flexbox','css',9,'Propriedade gap',
    `.container {\n  display: flex;\n  background-color: #f1f5f9;\n  padding: 16px;\n  /* adicione gap */\n}`,
    `function v(o,c){return c.includes('gap:');}v;`,
    'Antes do gap, espaçar itens flex exigia margin em cada filho — e remover a margem do primeiro ou último. gap foi criado para simplificar isso: você define o espaço uma vez no contêiner.',
    'gap: espaço automático entre itens',
    'gap define o espaço entre os flex items sem afectar as bordas do contêiner. Você pode usar um valor (para ambas as direções) ou dois (row-gap e column-gap). Funciona tanto em Flexbox quanto em Grid.',
    `.container {\n  display: flex;\n  gap: 16px; /* espaço entre todos os itens */\n}\n\n.grid {\n  display: grid;\n  gap: 24px 16px; /* row-gap: 24px, column-gap: 16px */\n}`,
    'gap vs margin: a vantagem',
    'gap é mais inteligente que margin: ele só cria espaço ENTRE itens, nunca nas bordas. Com margin: 8px em cada filho, o primeiro e o último teriam margem nas bordas do contêiner — indesejável. gap resolve isso elegantemente.',
    `/* Antes do gap (verboso): */\n.item + .item { margin-left: 16px; }\n\n/* Com gap (limpo): */\n.container { gap: 16px; }`,
    'Adicione gap: 16px ao .container flexbox. Observe o espaçamento automático entre os itens sem margin extra nas bordas.',
    chk('Qual a vantagem do gap em relação a usar margin nos filhos?',['gap é mais rápido de renderizar','gap não adiciona espaço nas bordas externas — só entre os itens','gap funciona apenas com porcentagem','margin não funciona em flex items'],1,'gap é mais semântico e limpo: adiciona espaço apenas ENTRE os items, nunca nas bordas. Com margin, o primeiro e último item ganham espaço indesejado nas bordas do contêiner.'),
    'Você usa gap! Junto com display: flex e justify-content, gap completa o trio básico do Flexbox. É a forma moderna e limpa de espaçar itens.',
    'c36','Crie .cards com display: flex, flex-wrap: wrap, gap: 24px e justify-content: center.',
    'gap vai no CONTÊINER (não nos filhos). Ele cria espaço entre todos os filhos.',
    'flex-wrap: wrap faz os itens quebrarem linha quando não cabem — combine com gap para espaçamento perfeito.',
    'Código:\n.cards { display: flex; flex-wrap: wrap; gap: 24px; justify-content: center; }'
  ),
];

// ─── Exportação dos módulos ────────────────────────────────────────────────────
export const cssPart1Modules: ModuleInput[] = [
  {
    title: 'Módulo 1: Introdução ao CSS',
    description: 'Entenda o que é CSS, como conectá-lo ao HTML e as bases dos seletores.',
    order: 1,
    lessons: mod1,
  },
  {
    title: 'Módulo 2: Aparência',
    description: 'Controle cores de texto, fundo, imagens, opacidade e gradientes.',
    order: 2,
    lessons: mod2,
  },
  {
    title: 'Módulo 3: Texto e Tipografia',
    description: 'Domine fontes, tamanhos, pesos, alinhamento e espaçamento tipográfico.',
    order: 3,
    lessons: mod3,
  },
  {
    title: 'Módulo 4: Espaçamento e Box Model',
    description: 'Aprenda margin, padding, border e o modelo de caixa CSS.',
    order: 4,
    lessons: mod4,
  },
  {
    title: 'Módulo 5: Seletores Avançados',
    description: 'Classes, IDs, seletores compostos, pseudo-classes e hover.',
    order: 5,
    lessons: mod5,
  },
  {
    title: 'Módulo 6: Layout com Flexbox',
    description: 'Construa layouts flexíveis e responsivos com Flexbox.',
    order: 6,
    lessons: mod6,
  },
];
